/** Arabic copy, keyed by the English source string. `{name}` placeholders are interpolated. */
export const ar: Record<string, string> = {
  "1 2y": "١–٢ سنة",
  "2 3y": "٢–٣ سنوات",
  "3y Plus": "٣ سنوات فأكثر",
  "80% range": "نطاق ٨٠٪",
  "A compound or developer…": "كمبوند أو مطوّر…",
  "A compound, developer, district, or page…": "كمبوند، مطوّر، منطقة، أو صفحة…",
  "A compound, developer, or district…": "كمبوند، مطوّر، أو منطقة…",
  "A developer or one of its compounds…": "مطوّر أو أحد كمبونداته…",
  "A fair-value layer for Egypt’s resale property market.": "طبقة قيمة عادلة لسوق إعادة بيع العقارات في مصر.",
  "A headline price": "السعر المُعلن",
  "A headline price on a long plan is not a cash price. Remaining installments are discounted at {rate} a year. For half of installment listings that removes at least {cut} from the headline.": "السعر المُعلن على خطة سداد طويلة ليس سعرًا كاش. نخصم الأقساط المتبقية بمعدل {rate} سنويًا. في نصف إعلانات التقسيط يقلّ ذلك السعر بما لا يقل عن {cut}.",
  "A level with n listings moves n ÷ (n + {k}) of the way from its parent, so a compound with four listings moves halfway. Unit adjustments are fitted jointly with the levels.": "المستوى الذي فيه n إعلان يتحرك بمقدار n ÷ (n + {k}) من المسافة بعيدًا عن المستوى الأعلى، فالكمبوند الذي فيه أربعة إعلانات يتحرك نصف المسافة. وتُقدَّر تعديلات الوحدة مع المستويات معًا.",
  "A little off the map": "ابتعدنا قليلًا عن الخريطة",
  "A · compound level": "A – على مستوى الكمبوند",
  "Above fair range": "أعلى من النطاق العادل",
  "Accuracy": "الدقة",
  "Across {n} valued units, like for like": "عبر {n} وحدة مُقيَّمة، مقارنة بالمثل",
  "Added to comparison": "أُضيف إلى المقارنة",
  "Added to your watchlist": "أُضيف إلى قائمة المتابعة",
  "Adjust the details and re-value": "عدّل التفاصيل وأعد التقييم",
  "Adjusted for unit type, finishing, delivery and size. Developers with at least 40 resale listings.": "بعد التعديل حسب نوع الوحدة والتشطيب والتسليم والمساحة. للمطورين الذين لديهم ٤٠ إعلان إعادة بيع على الأقل.",
  "Against a finished unit": "مقارنةً بوحدة متشطبة",
  "Against a ready unit, after converting to cash": "مقارنةً بوحدة استلام فوري، بعد التحويل إلى كاش",
  "Against an apartment, chalet or villa in the same place": "مقارنةً بشقة أو شاليه أو فيلا في المكان نفسه",
  "All compounds": "كل الكمبوندات",
  "All developers": "كل المطورين",
  "All districts": "كل المناطق",
  "All unit types": "كل أنواع الوحدات",
  "All units": "كل الوحدات",
  "All {n} units": "كل الوحدات ({n})",
  "All-in cost in today’s money": "التكلفة الشاملة بقيمة اليوم",
  "An original source link was not provided.": "لم يتوفر رابط المصدر الأصلي.",
  "Any evidence": "أي درجة دليل",
  "Any payment": "أي طريقة سداد",
  "Any position": "أي موقع",
  "Apartment": "شقة",
  "Apartments": "شقق",
  "Area": "المساحة",
  "Area (m²)": "المساحة (م²)",
  "Ask the seller and the developer about each of these before you commit.": "اسأل البائع والمطوّر عن كل بند من هذه قبل أن تلتزم.",
  "Asking": "مطلوب",
  "Asking price": "السعر المطلوب",
  "Asking price per m²": "السعر المطلوب للمتر",
  "Asking prices, not sale prices": "أسعار مطلوبة، لا أسعار بيع",
  "B · developer level": "B – على مستوى المطوّر",
  "Backtest by evidence grade": "الاختبار الرجعي حسب درجة الدليل",
  "Based on {n} listings": "مبني على {n} إعلان",
  "Bathrooms": "الحمامات",
  "Bedrooms": "غرف النوم",
  "Below fair range": "أقل من النطاق العادل",
  "Below or above means the cash-equivalent price falls outside the range that held 80% of comparable units in our backtest. It is a prompt to look closer, not a recommendation.": "«أقل» أو «أعلى» يعني أن السعر المكافئ للكاش يقع خارج النطاق الذي ضمّ ٨٠٪ من الوحدات المماثلة في اختبارنا الرجعي. إنها دعوة للتدقيق، لا توصية.",
  "Brokerage": "عمولة السمسرة",
  "Browse compounds": "تصفّح الكمبوندات",
  "Browse developers": "تصفّح المطورين",
  "Building": "مبنى",
  "C · district level": "C – على مستوى المنطقة",
  "Cabin": "كابينة",
  "Cash": "كاش",
  "Cash equivalent": "المكافئ النقدي",
  "Cash needed at signing": "الكاش المطلوب عند التعاقد",
  "Cash today": "كاش اليوم",
  "Cash-equivalent price {price}": "السعر المكافئ للكاش {price}",
  "Chalet": "شاليه",
  "Chalets": "شاليهات",
  "Charged by the developer to move the contract to you": "يحصّلها المطوّر لنقل العقد باسمك",
  "Check this listing": "راجع هذا الإعلان",
  "Choose a compound, or a district if the unit is not in one.": "اختر كمبوندًا، أو منطقة إن لم تكن الوحدة في كمبوند.",
  "Choose a district": "اختر منطقة",
  "Clear all": "مسح الكل",
  "Clear filters": "مسح عوامل التصفية",
  "Clear search": "مسح البحث",
  "Clinic": "عيادة",
  "Close search": "إغلاق البحث",
  "Closest comparable listings": "أقرب الإعلانات المماثلة",
  "Collection status": "حالة الجمع",
  "Commercial": "تجاري",
  "Comparable listings": "إعلانات مماثلة",
  "Compare": "قارن",
  "Compare compounds with compounds, and developers with developers.": "قارن الكمبوندات بالكمبوندات، والمطورين بالمطورين.",
  "Compare up to three compounds, or up to three developers, on fair value, delivery and payment structure.": "قارن حتى ثلاثة كمبوندات أو ثلاثة مطورين من حيث القيمة العادلة والتسليم وهيكل السداد.",
  "Compared on a cash-equivalent basis: remaining installments discounted to today’s money.": "المقارنة على أساس المكافئ النقدي: الأقساط المتبقية مخصومة إلى قيمة اليوم.",
  "Comparison": "المقارنة",
  "Complete run": "دورة جمع مكتملة",
  "Compound": "الكمبوند",
  "Compound first,": "الكمبوند أولًا،",
  "Compound-level evidence": "دليل على مستوى الكمبوند",
  "Compounds": "الكمبوندات",
  "Compounds with their fair value and premium": "الكمبوندات بقيمتها العادلة وعلاوتها",
  "Convert to cash today": "حوّل إلى كاش اليوم",
  "Core Shell": "على الطوب",
  "Coverage": "التغطية",
  "Dates brought forward": "مواعيد قُدّمت",
  "Dates pushed later since we started watching": "مواعيد تأجّلت منذ بدأنا المتابعة",
  "Days of observation so far. Price trends, time on market and delivery delays are shown only once there are at least eight weeks of history.": "يومًا من الرصد حتى الآن. لا تظهر اتجاهات الأسعار ومدة البقاء في السوق وتأخيرات التسليم إلا بعد ثمانية أسابيع على الأقل من السجل.",
  "Delivery": "التسليم",
  "Delivery and payment": "التسليم والسداد",
  "Delivery date": "موعد التسليم",
  "Delivery reliability": "الالتزام بمواعيد التسليم",
  "Describe the unit": "صِف الوحدة",
  "Describe the unit you were offered. Qayem converts its payment plan to cash today and prices it against its own compound and developer.": "صِف الوحدة المعروضة عليك. يحوّل قيّم خطة سدادها إلى كاش اليوم ويسعّرها مقابل الكمبوند والمطوّر الخاصين بها.",
  "Developer": "المطوّر",
  "Developer or thin compound evidence": "دليل على مستوى المطوّر أو كمبوند قليل الإعلانات",
  "Developer premium vs district norm": "علاوة المطوّر مقابل متوسط المنطقة",
  "Developer transfer fee": "رسوم التنازل للمطوّر",
  "Developers": "المطورون",
  "Developers charge different transfer fees, and maintenance deposits may or may not be paid. The cost calculator uses editable assumptions.": "تختلف رسوم التنازل من مطوّر لآخر، وقد تكون وديعة الصيانة مدفوعة أو لا. حاسبة التكلفة تستخدم افتراضات قابلة للتعديل.",
  "Developers with their premium against district norms": "المطورون وعلاوتهم مقابل متوسط المناطق",
  "Different price": "سعر مختلف",
  "Different price.": "سعر مختلف.",
  "Dismiss notification": "إغلاق الإشعار",
  "District": "المنطقة",
  "District benchmark": "مرجع المنطقة",
  "District median per m²": "وسيط سعر المتر في المنطقة",
  "District median per m² (the naive method)": "وسيط سعر المتر في المنطقة (الطريقة البسيطة)",
  "District summary": "ملخص المنطقة",
  "District, if not in a known compound": "المنطقة، إن لم تكن في كمبوند معروف",
  "District-level evidence only": "دليل على مستوى المنطقة فقط",
  "Districts": "المناطق",
  "Duplex": "دوبلكس",
  "EGP": "ج.م",
  "Each level moves part of the way from the one above, in proportion to how many listings support it. A compound with few listings stays close to its developer’s norm.": "كل مستوى يبتعد جزئيًا عن المستوى الأعلى بقدر عدد الإعلانات التي تدعمه. الكمبوند قليل الإعلانات يبقى قريبًا من متوسط مطوّره.",
  "Each of {n} listings is valued with itself removed from the data, and the prediction is compared with its cash-equivalent asking price. The ranges shown on every unit are the 10th to 90th percentile of these errors.": "يُقيَّم كل إعلان من {n} إعلان بعد حذفه من البيانات، ثم يُقارن التقدير بسعره المطلوب المكافئ للكاش. النطاقات المعروضة على كل وحدة هي من المئين العاشر إلى التسعين لهذه الأخطاء.",
  "Each unit starts from its district, then its developer, then its compound, and is adjusted for unit type, finishing, delivery date and size.": "تبدأ كل وحدة من منطقتها، ثم مطوّرها، ثم الكمبوند، وتُعدَّل حسب نوع الوحدة والتشطيب وموعد التسليم والمساحة.",
  "Egypt publishes no resale transaction prices. A fair value is where comparable asking prices sit once payment plans are converted to cash, and final deals are often lower.": "لا تُنشر في مصر أسعار صفقات إعادة البيع. القيمة العادلة هي موقع الأسعار المطلوبة للوحدات المماثلة بعد تحويل خطط السداد إلى كاش، وكثيرًا ما تُغلق الصفقات بأقل من ذلك.",
  "Egypt-wide {class}": "{class} على مستوى مصر",
  "Enter an area between 20 and 5,000 m².": "أدخل مساحة بين ٢٠ و٥٬٠٠٠ م².",
  "Enter how many years of installments remain.": "أدخل عدد سنوات الأقساط المتبقية.",
  "Enter the full headline price in EGP.": "أدخل السعر المُعلن كاملًا بالجنيه.",
  "Evaluate": "قيّم",
  "Evaluate a unit": "قيّم وحدة",
  "Every fair value on Qayem comes from one published model, checked against units it has not seen. Here is the model, its accuracy, and what it cannot know.": "كل قيمة عادلة على قيّم تأتي من نموذج واحد منشور، مُختبر على وحدات لم يرها. هنا النموذج ودقته وما لا يمكنه معرفته.",
  "Every re-crawl compares each unit’s promised handover date with the last one we saw. A pattern of postponements is a risk signal that marketing never shows.": "في كل جولة جمع نقارن موعد التسليم الموعود لكل وحدة بآخر موعد رأيناه. تكرار التأجيل إشارة خطر لا تُظهرها الإعلانات أبدًا.",
  "Every resale unit,": "كل وحدة إعادة بيع،",
  "Every value carries an evidence grade and a range measured on held-out units. When the evidence is thin, we say so instead of guessing.": "كل قيمة تحمل درجة دليل ونطاقًا مقيسًا على وحدات مُستبعدة من التدريب. وحين يكون الدليل ضعيفًا نقول ذلك بدل التخمين.",
  "Evidence": "الدليل",
  "Fair cash / m²": "القيمة العادلة كاش / م²",
  "Fair cash value per m² for each compound, and how far it sits above or below comparable units in its district.": "القيمة العادلة كاش للمتر في كل كمبوند، ومدى ارتفاعها أو انخفاضها عن الوحدات المماثلة في منطقتها.",
  "Fair cash value, finished and ready, typical size": "القيمة العادلة كاش، متشطبة واستلام فوري، بمساحة معتادة",
  "Fair range": "النطاق العادل",
  "Fair range {low} to {high}; central estimate {fair}.": "النطاق العادل من {low} إلى {high}؛ التقدير المركزي {fair}.",
  "Fair value": "القيمة العادلة",
  "Fair value plus the same fees": "القيمة العادلة مع الرسوم نفسها",
  "Fair values are estimates built from published asking prices, not appraisals or completed sales. Confirm every detail with the seller and the developer.": "القيم العادلة تقديرات مبنية على أسعار مطلوبة منشورة، وليست تقييمات رسمية أو صفقات مكتملة. تحقّق من كل التفاصيل مع البائع والمطوّر.",
  "Family House": "بيت عائلة",
  "Fees differ by developer and deal. These are editable assumptions, as a share of the headline price.": "تختلف الرسوم حسب المطوّر والصفقة. هذه افتراضات قابلة للتعديل كنسبة من السعر المُعلن.",
  "Find this listing": "ابحث عن هذا الإعلان",
  "Finished": "متشطب",
  "Finishing": "التشطيب",
  "Finishing mix": "توزيع التشطيب",
  "Floor, view and orientation": "الدور والإطلالة والاتجاه",
  "Footer": "تذييل الصفحة",
  "Furnished": "مفروش",
  "Furthest below fair value first": "الأبعد تحت القيمة العادلة أولًا",
  "Go to": "انتقل إلى",
  "Headline above cash value by": "السعر المُعلن أعلى من قيمة الكاش بـ",
  "Headline price": "السعر المُعلن",
  "Headline price (EGP)": "السعر المُعلن (ج.م)",
  "Held-out accuracy": "الدقة على وحدات مُستبعدة",
  "Highest and lowest": "الأعلى والأدنى",
  "Highest premium": "أعلى علاوة",
  "History is still short": "السجل ما زال قصيرًا",
  "House": "منزل",
  "How a fair value": "كيف تُبنى القيمة العادلة",
  "How a unit is valued": "كيف تُقيَّم الوحدة",
  "How each developer’s resale units price against comparable units in the same districts, and what their stock looks like: delivery, payment plans and finishing.": "كيف تُسعَّر وحدات إعادة البيع لكل مطوّر مقابل الوحدات المماثلة في المناطق نفسها، وشكل المعروض لديه: التسليم وخطط السداد والتشطيب.",
  "How the fair value was built": "كيف بُنيت القيمة العادلة",
  "How to evaluate": "طريقة التقييم",
  "Identified resale": "إعادة بيع مؤكدة",
  "Identified resale listings with their cash-equivalent price, Qayem’s fair range and the strength of the evidence behind it.": "إعلانات إعادة البيع المؤكدة بسعرها المكافئ للكاش، والنطاق العادل من قيّم، وقوة الدليل وراءه.",
  "If a broker is involved": "إن كان هناك سمسار",
  "In 1–2 years": "خلال ١–٢ سنة",
  "In 2–3 years": "خلال ٢–٣ سنوات",
  "In 3+ years": "بعد ٣ سنوات أو أكثر",
  "In Egypt the developer and the compound set the price per m² as much as the neighbourhood does. Here is how each developer’s resale units price against comparable units in the same districts.": "في مصر يحدد المطوّر والكمبوند سعر المتر بقدر ما تحدده المنطقة. هكذا تُسعَّر وحدات إعادة البيع لكل مطوّر مقابل الوحدات المماثلة في المناطق نفسها.",
  "In comparison": "في الميزان",
  "In the listing’s own words": "بكلمات الإعلان نفسه",
  "In {n} years": "بعد {n} سنة",
  "In {year}": "في {year}",
  "Included: active sale listings in EGP between EGP 100,000 and 200 million, 20–5,000 m², with a property type and a district or compound. Only identified resale listings are valued by default. A complete run covers its defined scope, not the whole market.": "المشمول: إعلانات بيع نشطة بالجنيه بين ١٠٠ ألف و٢٠٠ مليون جنيه، بمساحة ٢٠–٥٬٠٠٠ م²، مع نوع عقار ومنطقة أو كمبوند. تُقيَّم افتراضيًا إعلانات إعادة البيع المؤكدة فقط. دورة الجمع المكتملة تغطي نطاقها المحدد، لا السوق كله.",
  "Indexed records": "السجلات المفهرسة",
  "Indexed records, resale listings and valued listings by source": "السجلات المفهرسة وإعلانات إعادة البيع والإعلانات المُقيَّمة حسب المصدر",
  "Installment plan": "خطة تقسيط",
  "Installment plans with known terms": "خطط تقسيط معروفة الشروط",
  "Installment term": "مدة التقسيط",
  "Installments": "تقسيط",
  "Installments, term not published": "تقسيط، والمدة غير منشورة",
  "Is this": "هل هذا",
  "Its compounds": "كمبونداته",
  "Kept in this browser only. No account, no enquiries sent to anyone.": "محفوظة في هذا المتصفح فقط. بلا حساب، ولا تُرسل أي استفسارات لأحد.",
  "Know the evidence": "اعرف الدليل",
  "Land": "أرض",
  "Last observed": "آخر رصد",
  "Latest promised delivery": "آخر موعد تسليم موعود",
  "Legal status": "الوضع القانوني",
  "Let’s try that again": "لنحاول مرة أخرى",
  "Likely range {low} – {high}": "النطاق المرجّح {low} – {high}",
  "Limits": "الحدود",
  "Listed on installment plans": "معروضة بخطط تقسيط",
  "Listing link": "رابط الإعلان",
  "Listings": "الإعلانات",
  "Listings, not unique units": "إعلانات، لا وحدات فريدة",
  "Localbusiness": "نشاط تجاري",
  "Loft": "لوفت",
  "Lowest premium": "أدنى علاوة",
  "Main class": "الفئة الرئيسية",
  "Main navigation": "القائمة الرئيسية",
  "Main source": "المصدر الرئيسي",
  "Maintenance deposit": "وديعة الصيانة",
  "Maintenance deposit status": "حالة وديعة الصيانة",
  "Measure": "المقياس",
  "Median asking / m²": "وسيط السعر المطلوب / م²",
  "Median cash-equivalent / m²": "وسيط المكافئ النقدي / م²",
  "Median error": "الخطأ الوسيط",
  "Median error on held-out units": "الخطأ الوسيط على وحدات مُستبعدة",
  "Median error on the same units": "الخطأ الوسيط على الوحدات نفسها",
  "Median error on the same {n} units": "الخطأ الوسيط على الوحدات نفسها ({n})",
  "Median gap between each unit’s cash-equivalent asking price and the value predicted without it, across {n} units.": "الفجوة الوسيطة بين السعر المطلوب المكافئ للكاش لكل وحدة والقيمة المتوقعة من دونها، عبر {n} وحدة.",
  "Median plan length": "المدة الوسيطة للخطة",
  "Median share still owed": "النسبة الوسيطة المتبقية للسداد",
  "Median wait for the rest": "الانتظار الوسيط لغير الجاهز",
  "Methodology": "المنهجية",
  "Model trained on": "دُرّب النموذج على",
  "Most identified resale listings come from one source. Figures describe the listings we index, not the whole Egyptian market.": "معظم إعلانات إعادة البيع المؤكدة تأتي من مصدر واحد. الأرقام تصف الإعلانات التي نفهرسها، لا السوق المصري كله.",
  "Most listings": "الأكثر إعلانات",
  "Name": "الاسم",
  "Next page": "الصفحة التالية",
  "No compound": "بلا كمبوند",
  "No compounds match.": "لا توجد كمبوندات مطابقة.",
  "No developers match.": "لا يوجد مطورون مطابقون.",
  "No units match.": "لا توجد وحدات مطابقة.",
  "Not available": "غير متاح",
  "Not enough evidence to value this unit.": "لا يوجد دليل كافٍ لتقييم هذه الوحدة.",
  "Not enough valued units yet": "لا توجد وحدات مُقيَّمة كافية بعد",
  "Not graded": "بلا درجة",
  "Not positioned": "غير محدد الموقع",
  "Not provided": "غير متوفر",
  "Not published": "غير منشور",
  "Not recorded": "غير مسجّل",
  "Not sure": "لست متأكدًا",
  "Not valued": "غير مُقيَّمة",
  "Nothing matches that yet.": "لا شيء يطابق ذلك بعد.",
  "Nothing on your watchlist yet.": "قائمة المتابعة فارغة.",
  "Nothing to compare yet.": "لا شيء للمقارنة بعد.",
  "Observation window": "فترة الرصد",
  "Off the map": "خارج الخريطة",
  "Office": "مكتب",
  "Often due at handover if the seller has not paid it": "غالبًا تُستحق عند الاستلام إن لم يدفعها البائع",
  "On plans": "بالتقسيط",
  "On this payment plan, a fair headline price would be about {fair} (listed at {price}).": "بهذه الخطة يكون السعر المُعلن العادل نحو {fair} (المعروض {price}).",
  "Only if you register the title": "فقط إن سجّلت الملكية",
  "Open a compound or developer and choose Compare.": "افتح كمبوندًا أو مطوّرًا واختر «قارن».",
  "Open a compound or developer and choose Watch.": "افتح كمبوندًا أو مطوّرًا واختر «تابِع».",
  "Or paste a listing link": "أو الصق رابط إعلان",
  "Other": "أخرى",
  "Over": "على مدى",
  "Overpayment plus the down payment already paid to the developer": "الأوفر مضافًا إليه المقدم المدفوع بالفعل للمطوّر",
  "Pages": "الصفحات",
  "Paid at signing": "المدفوع عند التعاقد",
  "Paid at signing (EGP)": "المدفوع عند التعاقد (ج.م)",
  "Paid later": "يُدفع لاحقًا",
  "Partial run": "دورة جمع جزئية",
  "Paste a link from Nawy, OpenSooq, Aqarmap, Semsar Masr, GPM or Coldwell Banker": "الصق رابطًا من ناوي أو السوق المفتوح أو عقارماب أو سمسار مصر أو GPM أو كولدويل بانكر",
  "Paste a listing link": "الصق رابط إعلان",
  "Payment": "السداد",
  "Payment terms": "شروط السداد",
  "Payment terms not published": "شروط السداد غير منشورة",
  "Penthouse": "بنتهاوس",
  "Plan discount": "خصم الخطة",
  "Plan, term unknown": "تقسيط، المدة غير معروفة",
  "Position": "الموقع",
  "Positioned against fair value": "محدد الموقع مقابل القيمة العادلة",
  "Preferences": "التفضيلات",
  "Premium against each district": "العلاوة مقابل كل منطقة",
  "Premium vs district": "العلاوة مقابل المنطقة",
  "Premium vs district norm": "العلاوة مقابل متوسط المنطقة",
  "Previous page": "الصفحة السابقة",
  "Price per m² is modelled in cash-equivalent terms. Each unit starts from its property class across Egypt, then moves towards its district, its developer within that district, and its compound, each by as much as the number of listings there justifies.": "يُنمذج سعر المتر بالمكافئ النقدي. تبدأ كل وحدة من فئتها على مستوى مصر، ثم تتجه نحو منطقتها، ثم مطوّرها داخل المنطقة، ثم الكمبوند، كلٌّ بقدر ما يبرره عدد الإعلانات هناك.",
  "Price per m² when the area doubles": "سعر المتر عند مضاعفة المساحة",
  "Price the compound, not the map": "سعّر الكمبوند، لا الخريطة",
  "Price trends, time on market and delivery postponements need repeated observation. They appear once there are eight weeks of history.": "اتجاهات الأسعار ومدة البقاء في السوق وتأجيلات التسليم تحتاج رصدًا متكررًا. تظهر بعد ثمانية أسابيع من السجل.",
  "Price trends, time on market and delivery-date changes appear after eight weeks of observation. Qayem has observed this market for {n} days.": "تظهر اتجاهات الأسعار ومدة البقاء في السوق وتغيّر مواعيد التسليم بعد ثمانية أسابيع من الرصد. رصد قيّم هذا السوق منذ {n} يوم.",
  "Priced against its district": "مُسعَّر مقابل منطقته",
  "Priced below / within / above range": "أقل من / ضمن / أعلى من النطاق",
  "Prices are what sellers ask, not what buyers paid. Egypt publishes no resale transaction prices, so a fair value is where comparable asking prices sit.": "الأسعار هي ما يطلبه البائعون، لا ما دفعه المشترون. لا تُنشر في مصر أسعار صفقات إعادة البيع، فالقيمة العادلة هي موقع الأسعار المطلوبة للوحدات المماثلة.",
  "Promised dates, tracked": "المواعيد الموعودة، تحت المتابعة",
  "Property types": "أنواع العقارات",
  "Qayem": "قيّم",
  "Qayem fair value · cash today": "القيمة العادلة من قيّم، كاش اليوم",
  "Qayem has observed this market for {n} days.": "رصد قيّم هذا السوق منذ {n} يوم.",
  "Qayem home": "الصفحة الرئيسية لقيّم",
  "Qayem model": "نموذج قيّم",
  "Qayem values Egypt’s resale units by compound, developer, delivery date and payment plan, not by area alone, and tells you how sure it is.": "يقيّم قيّم وحدات إعادة البيع في مصر حسب الكمبوند والمطوّر وموعد التسليم وخطة السداد، لا بالمساحة وحدها، ويخبرك بمدى ثقته.",
  "Qayem weighs Egypt's resale property market: every listing scored, sourced, and priced against its peers.": "قيّم يقدّر القيمة العادلة لوحدات إعادة البيع في مصر حسب الكمبوند والمطوّر والتسليم وخطة السداد.",
  "Quick navigation": "تنقّل سريع",
  "Read full description": "اقرأ الوصف كاملًا",
  "Read the methodology": "اقرأ المنهجية",
  "Ready": "استلام فوري",
  "Ready now": "استلام فوري",
  "Ready to move in": "جاهزة للسكن",
  "Registration": "التسجيل",
  "Registration and contract status": "التسجيل ونوع العقد",
  "Registration, contract type and outstanding dues are not published. Confirm them with the developer before paying anything.": "التسجيل ونوع العقد والمستحقات المتأخرة غير منشورة. تأكد منها مع المطوّر قبل دفع أي مبلغ.",
  "Remove {name} from comparison": "إزالة {name} من المقارنة",
  "Remove {name} from your watchlist": "إزالة {name} من قائمة المتابعة",
  "Removed from comparison": "أُزيل من المقارنة",
  "Removed from your watchlist": "أُزيل من قائمة المتابعة",
  "Resale evidence": "دليل إعادة البيع",
  "Resale fair value": "القيمة العادلة لإعادة البيع",
  "Resale fair-value index": "مؤشر القيمة العادلة لإعادة البيع",
  "Resale listings": "إعلانات إعادة البيع",
  "Resale status unclassified": "حالة إعادة البيع غير مصنّفة",
  "Resale units": "وحدات إعادة البيع",
  "Resale units valued": "وحدات إعادة بيع مُقيَّمة",
  "Resale, with its evidence": "إعادة بيع، بدليلها",
  "Roof": "روف",
  "Same class of unit, nearest in size, from the same compound where possible. {cls}.": "من فئة الوحدة نفسها، الأقرب مساحةً، ومن الكمبوند نفسه متى أمكن. {cls}.",
  "Same district.": "المنطقة نفسها.",
  "Say how sure we are": "نقول مدى ثقتنا",
  "Search": "ابحث",
  "Search Qayem": "ابحث في قيّم",
  "Search compounds": "ابحث في الكمبوندات",
  "Search developers": "ابحث في المطورين",
  "Search units": "ابحث في الوحدات",
  "See its units": "اعرض وحداته",
  "See source coverage": "اطّلع على تغطية المصادر",
  "See the accuracy": "اطّلع على الدقة",
  "Semi Finished": "نصف تشطيب",
  "Shop": "محل",
  "Show less": "عرض أقل",
  "Side by side,": "جنبًا إلى جنب،",
  "Size": "المساحة",
  "Sizes from {min} to {max} m²": "مساحات من {min} إلى {max} م²",
  "Skip to content": "تخطَّ إلى المحتوى",
  "Sort by": "رتّب حسب",
  "Source": "المصدر",
  "Sources rarely publish them, so they are not in the model. A sea-view or garden unit can be worth well above its compound’s norm.": "نادرًا ما تنشرها المصادر، لذا ليست في النموذج. قد تساوي وحدة بإطلالة بحر أو بحديقة أكثر بكثير من متوسط الكمبوند.",
  "Start typing a compound name": "ابدأ بكتابة اسم الكمبوند",
  "Still owed": "المتبقي للسداد",
  "Stock on the resale market": "المعروض في سوق إعادة البيع",
  "Studio": "استوديو",
  "Switch to English": "Switch to English",
  "Terms unknown": "الشروط غير معروفة",
  "Tested on units": "مُختبر على وحدات",
  "That page isn’t here.": "هذه الصفحة غير موجودة.",
  "The amount paid at signing must be between 0 and the headline price.": "يجب أن يكون المدفوع عند التعاقد بين صفر والسعر المُعلن.",
  "The compound": "الكمبوند",
  "The compounds": "الكمبوندات",
  "The evidence": "الدليل",
  "The model": "النموذج",
  "The name on the gate": "الاسم على البوابة",
  "The payment plan, in today’s money": "خطة السداد بقيمة اليوم",
  "The price": "السعر",
  "The resale signal comes from a source field, a dedicated resale catalogue, or a keyword. It is shown on every unit.": "إشارة إعادة البيع مصدرها حقل في المصدر أو كتالوج مخصص لإعادة البيع أو كلمة مفتاحية، وتظهر على كل وحدة.",
  "The same unit can appear on several platforms or be listed twice by different brokers. Counts are listings.": "قد تظهر الوحدة نفسها على عدة منصات أو يعرضها سمساران مختلفان. الأعداد أعداد إعلانات.",
  "The unit": "الوحدة",
  "This page is not available.": "هذه الصفحة غير متاحة.",
  "Three steps,": "ثلاث خطوات،",
  "Too little evidence, or not a residential unit. We do not guess.": "دليل غير كافٍ، أو ليست وحدة سكنية. نحن لا نخمّن.",
  "Total cost of buying": "التكلفة الإجمالية للشراء",
  "Townhouse": "تاون هاوس",
  "Transfer fees and deposits": "رسوم التنازل والودائع",
  "Try a different name or district.": "جرّب اسمًا أو منطقة مختلفة.",
  "Try a different name.": "جرّب اسمًا مختلفًا.",
  "Try again": "حاول مرة أخرى",
  "Try fewer filters or a broader search.": "جرّب عوامل تصفية أقل أو بحثًا أوسع.",
  "Twinhouse": "توين هاوس",
  "Typical valuation error": "خطأ التقييم المعتاد",
  "Unavailable · retry": "غير متاح، أعد المحاولة",
  "Under 1 Year": "خلال سنة",
  "Unit": "الوحدة",
  "Unit type": "نوع الوحدة",
  "Unit valuation": "تقييم الوحدة",
  "Units": "الوحدات",
  "Units in this compound": "الوحدات في هذا الكمبوند",
  "Units matching “{q}”": "وحدات تطابق «{q}»",
  "Units tested": "الوحدات المختبرة",
  "Units with a promised delivery date": "وحدات لها موعد تسليم موعود",
  "Units with their fair-value range": "الوحدات مع نطاق قيمتها العادلة",
  "Unknown": "غير معروف",
  "Valuation": "التقييم",
  "Value a unit": "قيّم وحدة",
  "Value a unit here": "قيّم وحدة هنا",
  "Value this unit": "قيّم هذه الوحدة",
  "Valued": "مُقيَّمة",
  "Valuing the unit…": "جارٍ تقييم الوحدة…",
  "View on {source}": "اعرض على {source}",
  "Villa": "فيلا",
  "Villas & houses": "فيلات ومنازل",
  "Vs district": "مقابل المنطقة",
  "Vs district is the average gap between the developer’s units and the benchmark for the same class in the same district, after adjusting for unit type, finishing, delivery and size. It needs at least five valued units, and twenty to appear in a premium ranking.": "«مقابل المنطقة» هو متوسط الفجوة بين وحدات المطوّر ومرجع الفئة نفسها في المنطقة نفسها، بعد التعديل حسب نوع الوحدة والتشطيب والتسليم والمساحة. يحتاج خمس وحدات مُقيَّمة على الأقل، وعشرين للظهور في ترتيب العلاوات.",
  "Warehouse": "مخزن",
  "Watch": "تابِع",
  "Watching": "قيد المتابعة",
  "Watchlist": "قائمة المتابعة",
  "We could not load the data. Please try again.": "تعذّر تحميل البيانات. حاول مرة أخرى.",
  "We do not recognise that developer.": "لا نعرف هذا المطوّر.",
  "We have no resale listings for that compound, so it is valued at district level.": "ليس لدينا إعلانات إعادة بيع لهذا الكمبوند، لذا يُقيَّم على مستوى المنطقة.",
  "We have no resale listings in that district.": "ليس لدينا إعلانات إعادة بيع في هذه المنطقة.",
  "We have not indexed that listing link. Enter its details instead.": "لم نفهرس رابط هذا الإعلان. أدخل تفاصيله بدلًا من ذلك.",
  "Weighing the market…": "جارٍ وزن السوق…",
  "What a fair value": "ما لا يمكن",
  "What is it": "كم تساوي",
  "What its resale stock looks like": "كيف يبدو معروضه لإعادة البيع",
  "What this is built on,": "على ماذا بُني هذا،",
  "What this valuation cannot see": "ما لا يراه هذا التقييم",
  "What was paid at signing counts in full. The balance is spread over the remaining term in quarterly installments and discounted at {rate} a year, roughly what the same money earns in Egyptian deposits.": "المدفوع عند التعاقد يُحتسب كاملًا. يُوزَّع الباقي على المدة المتبقية بأقساط ربع سنوية ويُخصم بمعدل {rate} سنويًا، وهو تقريبًا ما يكسبه المبلغ نفسه في الودائع المصرية.",
  "What you are really buying": "ما الذي تشتريه فعلًا",
  "Where": "المكان",
  "Where the evidence": "من أين يأتي",
  "Which compound is the unit in?": "في أي كمبوند الوحدة؟",
  "Why area alone misleads": "لماذا تضلّل المساحة وحدها",
  "Within a year": "خلال سنة",
  "Within fair range": "ضمن النطاق العادل",
  "Within ±10%": "ضمن ±١٠٪",
  "Within ±20%": "ضمن ±٢٠٪",
  "Worth today": "قيمتها اليوم",
  "Years of installments left": "سنوات الأقساط المتبقية",
  "You can compare up to 3. Remove one to add another.": "يمكنك مقارنة ٣ على الأكثر. أزل واحدًا لإضافة آخر.",
  "You will see a fair cash value with a likely range, what the payment plan is worth today, how the value was built, and the comparable listings behind it.": "سترى قيمة عادلة كاش مع نطاق مرجّح، وقيمة خطة السداد اليوم، وكيف بُنيت القيمة، والإعلانات المماثلة وراءها.",
  "Your selection will last for this visit only. Browser storage is unavailable.": "سيبقى اختيارك لهذه الزيارة فقط؛ تخزين المتصفح غير متاح.",
  "Your valuation appears here": "يظهر تقييمك هنا",
  "Your watchlist holds up to 100 entries.": "تتسع قائمة المتابعة لـ١٠٠ عنصر.",
  "a fair price?": "سعرًا عادلًا؟",
  "cannot tell you.": "للقيمة العادلة أن تخبرك به.",
  "comes from.": "الدليل.",
  "every unit.": "لكل وحدة.",
  "fair cash / m²": "القيمة العادلة كاش / م²",
  "fees {share}": "الرسوم {share}",
  "is built, and tested.": "وكيف تُختبر.",
  "is not a cash price.": "ليس سعرًا كاش.",
  "is priced in.": "له ثمن.",
  "it has not seen.": "لم يرها.",
  "like for like.": "بالمثل.",
  "loading…": "جارٍ التحميل…",
  "m²": "م²",
  "observed {date}": "رُصد {date}",
  "plainly.": "بوضوح.",
  "really worth?": "فعلًا؟",
  "sets the price.": "يحدد السعر.",
  "then the unit.": "ثم الوحدة.",
  "to move": "للتنقل",
  "to open": "للفتح",
  "valued.": "مُقيَّمة.",
  "vs district": "مقابل المنطقة",
  "you care about.": "التي تهمّك.",
  "{developer}: {premium} vs district across {n} listings": "{developer}: {premium} مقابل المنطقة عبر {n} إعلان",
  "{label} compound": "كمبوند {label}",
  "{label} district": "منطقة {label}",
  "{label} in this district": "{label} في هذه المنطقة",
  "{n} bed": "غرفة واحدة",
  "{n} beds": "{n} غرف",
  "{n} compounds": "{n} كمبوند",
  "{n} districts": "{n} منطقة",
  "{n} further compounds have too few listings for a premium.": "{n} كمبوند آخر إعلاناته أقل من أن تُحسب له علاوة.",
  "{n} listings": "{n} إعلان",
  "{n} listings · {change}": "{n} إعلان، {change}",
  "{n} m² vs typical {typical} m²": "{n} م² مقابل {typical} م² معتادة",
  "{n} sources": "{n} مصادر",
  "{n} units": "{n} وحدة",
  "{n} years": "{n} سنة",
  "{n}-year plan": "خطة {n} سنة",
  "{premium} against comparable units in {district}": "{premium} مقابل الوحدات المماثلة في {district}",
  "{share} from {source}": "{share} من {source}",
  "{start}–{end} of {total} compounds": "{start}–{end} من {total} كمبوند",
  "{start}–{end} of {total} developers": "{start}–{end} من {total} مطوّر",
  "{start}–{end} of {total} units": "{start}–{end} من {total} وحدة",
  "Payment plan": "خطة السداد",
  "Cash-equivalent price against a cash unit": "السعر المكافئ للكاش مقارنةً بوحدة كاش",
  "Under 3 years left": "أقل من ٣ سنوات متبقية",
  "3–6 years left": "٣–٦ سنوات متبقية",
  "6–9 years left": "٦–٩ سنوات متبقية",
  "9+ years left": "٩ سنوات فأكثر متبقية",
  "Term not published": "المدة غير منشورة",
  "For the median installment listing the cash value is {cut} below the headline. When terms are not fully published the unit is valued but its price is not positioned: classified listings often show only what is due now.": "في إعلان التقسيط الوسيط تقل القيمة كاش عن السعر المُعلن بنسبة {cut}. حين لا تُنشر الشروط كاملة تُقيَّم الوحدة دون تحديد موقع سعرها، فإعلانات المبوبة كثيرًا ما تعرض المستحق الآن فقط.",
  "These effects are fitted from the data, not assumed. The payment-plan effect shows how buyers actually price long plans: less steeply than a flat discount rate. Listings more than 2.5× away from their district norm are excluded from fitting and flagged “check this listing”.": "هذه التأثيرات مقدَّرة من البيانات لا مفترضة. يُظهر تأثير خطة السداد كيف يسعّر المشترون الخطط الطويلة فعلًا: بخصم أخف من معدل ثابت. الإعلانات التي تبعد أكثر من ٢٫٥ ضعف عن متوسط منطقتها تُستبعد من التقدير وتُعلَّم «راجع هذا الإعلان».",
  "The payment terms were not fully published, so the asking price is not placed against the range. Classified listings often show only what is due now, not the remaining installments.": "لم تُنشر شروط السداد كاملة، لذا لا يُحدَّد موقع السعر المطلوب من النطاق. إعلانات المبوبة كثيرًا ما تعرض المستحق الآن فقط، لا الأقساط المتبقية.",
  "Too few comparable listings outside compounds in this district.": "إعلانات مماثلة خارج الكمبوندات في هذه المنطقة أقل من اللازم.",
  "Too few comparable listings in this district and class.": "إعلانات مماثلة من هذه الفئة في هذه المنطقة أقل من اللازم.",
  "Qayem values apartments, chalets and houses only.": "يقيّم قيّم الشقق والشاليهات والمنازل فقط.",
  "Choose a known compound or district.": "اختر كمبوندًا أو منطقة معروفة.",
  "This unit is unavailable or does not meet the published inclusion rules.": "هذه الوحدة غير متاحة أو لا تستوفي قواعد الإدراج المنشورة.",
  "Choose a compound or a district.": "اختر كمبوندًا أو منطقة.",
  "The down payment cannot exceed the total price.": "لا يمكن أن يتجاوز المدفوع عند التعاقد السعر الإجمالي.",
  "We have no identified resale listings for this compound.": "ليس لدينا إعلانات إعادة بيع مؤكدة لهذا الكمبوند.",
  "We have no identified resale listings for this developer.": "ليس لدينا إعلانات إعادة بيع مؤكدة لهذا المطوّر.",
  "We have no identified resale listings for this district.": "ليس لدينا إعلانات إعادة بيع مؤكدة في هذه المنطقة.",
  "Qayem dataset is unavailable. Set QAYEM_DB to an existing Qayem database.": "بيانات قيّم غير متاحة حاليًا.",
  "Price trends, time on market and delivery-date changes appear after eight weeks of observation. Qayem has observed this market for {n} day.": "تظهر اتجاهات الأسعار ومدة البقاء في السوق وتغيّر مواعيد التسليم بعد ثمانية أسابيع من الرصد. رصد قيّم هذا السوق منذ يوم واحد.",
  "Qayem has observed this market for {n} day.": "رصد قيّم هذا السوق منذ يوم واحد.",
  "No current developer launch units could be matched to this compound.": "لم نتمكن من مطابقة وحدات إطلاق حالية من المطوّر مع هذا الكمبوند.",
  "No current launch units from this developer could be matched to a resale compound.": "لم نتمكن من مطابقة وحدات إطلاق حالية لهذا المطوّر مع كمبوند في سوق إعادة البيع.",
  "Buying new from the developer costs this much more than the resale market pays for the same unit, in today’s money.": "الشراء الجديد من المطوّر أغلى بهذه النسبة مما يدفعه سوق إعادة البيع في الوحدة نفسها، بقيمة اليوم.",
  "Buying new from the developer costs this much less than the resale market pays for the same unit, in today’s money.": "الشراء الجديد من المطوّر أرخص بهذه النسبة مما يدفعه سوق إعادة البيع في الوحدة نفسها، بقيمة اليوم.",
  "Launch headline / m²": "سعر الإطلاق المُعلن / م²",
  "Launch cash-equivalent / m²": "المكافئ النقدي لسعر الإطلاق / م²",
  "Typical launch plan": "خطة الإطلاق المعتادة",
  "{down} down, {n} years": "مقدم {down}، على {n} سنة",
  "Latest launch delivery": "آخر موعد تسليم للإطلاق",
  "Launch units compared": "وحدات الإطلاق المقارنة",
  "Phases": "المراحل",
  "Launch units are priced against the model’s resale value for the same compound, unit type, finishing, delivery date, plan length and size. Launch prices are list prices; negotiated developer discounts are not visible.": "تُقارن وحدات الإطلاق بقيمة النموذج لإعادة البيع للكمبوند ونوع الوحدة والتشطيب وموعد التسليم ومدة الخطة والمساحة نفسها. أسعار الإطلاق أسعار قوائم، ولا تظهر خصومات المطوّر المتفاوض عليها.",
  "Resale vs buying new": "إعادة البيع مقابل الشراء الجديد",
  "Against the developer’s launch price": "مقارنةً بسعر إطلاق المطوّر",
  "Against the developer’s launch prices": "مقارنةً بأسعار إطلاق المطوّر",
  "Vs launch": "مقابل الإطلاق",
  "Fair cash / m² is for a finished, ready unit of typical size in the compound’s most listed class. Vs district compares it with the district’s own benchmark for the same class. Plan discount is how far the median installment headline sits above its value in today’s money. Vs launch is how far the developer’s current launch price sits above what the resale market pays for the same unit.": "القيمة العادلة كاش / م² لوحدة متشطبة استلام فوري بمساحة معتادة من الفئة الأكثر عرضًا في الكمبوند. «مقابل المنطقة» يقارنها بمرجع المنطقة للفئة نفسها. «خصم الخطة» هو مقدار ارتفاع السعر المُعلن الوسيط للتقسيط عن قيمته اليوم. «مقابل الإطلاق» هو مقدار ارتفاع سعر إطلاق المطوّر الحالي عما يدفعه سوق إعادة البيع في الوحدة نفسها.",
  "Launch prices are list prices": "أسعار الإطلاق أسعار قوائم",
  "Developer launch prices come from the developers’ own current listings on Nawy. Negotiated discounts and private offers are not visible.": "تأتي أسعار إطلاق المطورين من إعلاناتهم الحالية على ناوي. لا تظهر الخصومات المتفاوض عليها والعروض الخاصة.",
  "{n} current developer launch units in {c} compounds are compared with the model’s resale value for the same unit on the same plan. The median launch unit costs {spread} against resale, in today’s money.": "قورنت {n} وحدة إطلاق حالية في {c} كمبوند بقيمة النموذج لإعادة البيع للوحدة نفسها بالخطة نفسها. وحدة الإطلاق الوسيطة تكلّف {spread} مقارنةً بإعادة البيع، بقيمة اليوم.",
  "Nawy (developer launches)": "ناوي (إطلاقات المطورين)",
  "Contract and receipts verified by AqarExit": "العقد والإيصالات متحقق منها بواسطة عقار إكزت",
  "Launch plans are long and back-loaded, so the comparison depends on how the model prices such plans. {n} resale units carry launch-like plans (85% or more still owed, seven or more years); the model values them with a median bias of {bias}.": "خطط الإطلاق طويلة ومؤجلة السداد، لذا تعتمد المقارنة على كيفية تسعير النموذج لمثل هذه الخطط. تحمل {n} وحدة إعادة بيع خططًا شبيهة بالإطلاق (٨٥٪ أو أكثر متبقٍ، وسبع سنوات أو أكثر)، ويقيّمها النموذج بانحياز وسيط قدره {bias}.",
};
