/** Arabic copy, keyed by the English source string. `{name}` placeholders are interpolated. */
export const ar: Record<string, string> = {
  "1 2y": "١–٢ سنة",
  "2 3y": "٢–٣ سنوات",
  "3y Plus": "٣ سنوات فأكثر",
  "80% range": "نطاق ٨٠٪",
  "A compound or developer…": "كمبوند أو مطوّر…",
  "A compound, developer, district, or page…": "كمبوند، مطوّر، منطقة، أو صفحة…",
  "A compound, developer, or district…": "كمبوند، مطوّر، أو منطقة…",
  "A developer or one of its compounds…": "مطوّر أو أحد كمبونداته…",
  "A fair-value layer for Egypt’s resale property market.": "طبقة قيمة عادلة لسوق إعادة بيع العقارات في مصر.",
  "A headline price": "السعر المُعلن",
  "A headline price on a long plan is not a cash price. Remaining installments are discounted at {rate} a year. For half of installment listings that removes at least {cut} from the headline.": "السعر المُعلن على خطة سداد طويلة ليس سعرًا كاش. نخصم الأقساط المتبقية بمعدل {rate} سنويًا. في نصف إعلانات التقسيط يقلّ ذلك السعر بما لا يقل عن {cut}.",
  "A level with n listings moves {share} of the way from its parent, so a compound with four listings moves halfway. Unit adjustments are fitted jointly with the levels.": "المستوى الذي فيه n إعلان يتحرك بمقدار {share} من المسافة بعيدًا عن المستوى الأعلى، فالكمبوند الذي فيه أربعة إعلانات يتحرك نصف المسافة. وتُقدَّر تعديلات الوحدة مع المستويات معًا.",
  "A little off the map": "ابتعدنا قليلًا عن الخريطة",
  "A · compound level": "A – على مستوى الكمبوند",
  "Above fair range": "أعلى من النطاق العادل",
  "Accuracy": "الدقة",
  "Across {n} valued units, like for like": "عبر {n} وحدة مُقيَّمة، مقارنة بالمثل",
  "Added to comparison": "أُضيف إلى المقارنة",
  "Added to your watchlist": "أُضيف إلى قائمة المتابعة",
  "Adjust the details and re-value": "عدّل التفاصيل وأعد التقييم",
  "Adjusted for unit type, finishing, delivery and size. Developers with at least 40 resale listings.": "بعد التعديل حسب نوع الوحدة والتشطيب والتسليم والمساحة. للمطورين الذين لديهم ٤٠ إعلان إعادة بيع على الأقل.",
  "Against a finished unit": "مقارنةً بوحدة متشطبة",
  "Against a ready unit, after converting to cash": "مقارنةً بوحدة استلام فوري، بعد التحويل إلى كاش",
  "Against an apartment, chalet or villa in the same place": "مقارنةً بشقة أو شاليه أو فيلا في المكان نفسه",
  "All compounds": "كل الكمبوندات",
  "All developers": "كل المطورين",
  "All districts": "كل المناطق",
  "All unit types": "كل أنواع الوحدات",
  "All units": "كل الوحدات",
  "All {n} units": "كل الوحدات ({n})",
  "All-in cost in today’s money": "التكلفة الشاملة بقيمة اليوم",
  "An original source link was not provided.": "لم يتوفر رابط المصدر الأصلي.",
  "Any evidence": "أي درجة دليل",
  "Any payment": "أي طريقة سداد",
  "Any position": "أي موقع",
  "Apartment": "شقة",
  "Apartments": "شقق",
  "Area": "المساحة",
  "Area (m²)": "المساحة (م²)",
  "Ask the seller and the developer about each of these before you commit.": "اسأل البائع والمطوّر عن كل بند من هذه قبل أن تلتزم.",
  "Asking": "مطلوب",
  "Asking price": "السعر المطلوب",
  "Asking price per m²": "السعر المطلوب للمتر",
  "Asking prices, not sale prices": "أسعار مطلوبة، لا أسعار بيع",
  "B · developer level": "B – على مستوى المطوّر",
  "Backtest by evidence grade": "الاختبار الرجعي حسب درجة الدليل",
  "Based on {n} listings": "مبني على {n} إعلان",
  "Bathrooms": "الحمامات",
  "Bedrooms": "غرف النوم",
  "Below fair range": "أقل من النطاق العادل",
  "Below or above means the cash-equivalent price falls outside the range that held 80% of comparable units in our backtest. It is a prompt to look closer, not a recommendation.": "«أقل» أو «أعلى» يعني أن السعر المكافئ للكاش يقع خارج النطاق الذي ضمّ ٨٠٪ من الوحدات المماثلة في اختبارنا الرجعي. إنها دعوة للتدقيق، لا توصية.",
  "Brokerage": "عمولة السمسرة",
  "Browse compounds": "تصفّح الكمبوندات",
  "Browse developers": "تصفّح المطورين",
  "Building": "مبنى",
  "C · district level": "C – على مستوى المنطقة",
  "Cabin": "كابينة",
  "Cash": "كاش",
  "Cash equivalent": "المكافئ النقدي",
  "Cash needed at signing": "الكاش المطلوب عند التعاقد",
  "Cash today": "كاش اليوم",
  "Cash-equivalent price {price}": "السعر المكافئ للكاش {price}",
  "Chalet": "شاليه",
  "Chalets": "شاليهات",
  "Charged by the developer to move the contract to you": "يحصّلها المطوّر لنقل العقد باسمك",
  "Check this listing": "راجع هذا الإعلان",
  "Choose a compound, or a district if the unit is not in one.": "اختر كمبوندًا، أو منطقة إن لم تكن الوحدة في كمبوند.",
  "Choose a district": "اختر منطقة",
  "Clear all": "مسح الكل",
  "Clear filters": "مسح عوامل التصفية",
  "Clear search": "مسح البحث",
  "Clinic": "عيادة",
  "Close search": "إغلاق البحث",
  "Closest comparable listings": "أقرب الإعلانات المماثلة",
  "Collection status": "حالة الجمع",
  "Commercial": "تجاري",
  "Comparable listings": "إعلانات مماثلة",
  "Compare": "قارن",
  "Compare compounds with compounds, and developers with developers.": "قارن الكمبوندات بالكمبوندات، والمطورين بالمطورين.",
  "Compare up to three compounds, or up to three developers, on fair value, delivery and payment structure.": "قارن حتى ثلاثة كمبوندات أو ثلاثة مطورين من حيث القيمة العادلة والتسليم وهيكل السداد.",
  "Compared on a cash-equivalent basis: remaining installments discounted to today’s money.": "المقارنة على أساس المكافئ النقدي: الأقساط المتبقية مخصومة إلى قيمة اليوم.",
  "Comparison": "المقارنة",
  "Complete run": "دورة جمع مكتملة",
  "Compound": "الكمبوند",
  "Compound first,": "الكمبوند أولًا،",
  "Compound-level evidence": "دليل على مستوى الكمبوند",
  "Compounds": "الكمبوندات",
  "Compounds with their fair value and premium": "الكمبوندات بقيمتها العادلة وعلاوتها",
  "Convert to cash today": "حوّل إلى كاش اليوم",
  "Core Shell": "على الطوب",
  "Coverage": "التغطية",
  "Dates brought forward": "مواعيد قُدّمت",
  "Dates pushed later since we started watching": "مواعيد تأجّلت منذ بدأنا المتابعة",
  "Days of observation so far. Price trends, time on market and delivery delays are shown only once there are at least eight weeks of history.": "يومًا من الرصد حتى الآن. لا تظهر اتجاهات الأسعار ومدة البقاء في السوق وتأخيرات التسليم إلا بعد ثمانية أسابيع على الأقل من السجل.",
  "Delivery": "التسليم",
  "Delivery and payment": "التسليم والسداد",
  "Delivery date": "موعد التسليم",
  "Delivery reliability": "الالتزام بمواعيد التسليم",
  "Describe the unit": "صِف الوحدة",
  "Describe the unit you were offered. Qayem converts its payment plan to cash today and prices it against its own compound and developer.": "صِف الوحدة المعروضة عليك. يحوّل قيّم خطة سدادها إلى كاش اليوم ويسعّرها مقابل الكمبوند والمطوّر الخاصين بها.",
  "Developer": "المطوّر",
  "Developer or thin compound evidence": "دليل على مستوى المطوّر أو كمبوند قليل الإعلانات",
  "Developer premium vs district norm": "علاوة المطوّر مقابل متوسط المنطقة",
  "Developer transfer fee": "رسوم التنازل للمطوّر",
  "Developers": "المطورون",
  "Developers charge different transfer fees, and maintenance deposits may or may not be paid. The cost calculator uses editable assumptions.": "تختلف رسوم التنازل من مطوّر لآخر، وقد تكون وديعة الصيانة مدفوعة أو لا. حاسبة التكلفة تستخدم افتراضات قابلة للتعديل.",
  "Developers with their premium against district norms": "المطورون وعلاوتهم مقابل متوسط المناطق",
  "Different price": "سعر مختلف",
  "Different price.": "سعر مختلف.",
  "Dismiss notification": "إغلاق الإشعار",
  "District": "المنطقة",
  "District benchmark": "مرجع المنطقة",
  "District median per m²": "وسيط سعر المتر في المنطقة",
  "District median per m² (the naive method)": "وسيط سعر المتر في المنطقة (الطريقة البسيطة)",
  "District summary": "ملخص المنطقة",
  "District, if not in a known compound": "المنطقة، إن لم تكن في كمبوند معروف",
  "District-level evidence only": "دليل على مستوى المنطقة فقط",
  "Districts": "المناطق",
  "Duplex": "دوبلكس",
  "EGP": "ج.م",
  "Each level moves part of the way from the one above, in proportion to how many listings support it. A compound with few listings stays close to its developer’s norm.": "كل مستوى يبتعد جزئيًا عن المستوى الأعلى بقدر عدد الإعلانات التي تدعمه. الكمبوند قليل الإعلانات يبقى قريبًا من متوسط مطوّره.",
  "Each of {n} listings is valued with itself removed from the data, and the prediction is compared with its cash-equivalent asking price. The ranges shown on every unit are the 10th to 90th percentile of these errors.": "يُقيَّم كل إعلان من {n} إعلان بعد حذفه من البيانات، ثم يُقارن التقدير بسعره المطلوب المكافئ للكاش. النطاقات المعروضة على كل وحدة هي من المئين العاشر إلى التسعين لهذه الأخطاء.",
  "Each unit starts from its district, then its developer, then its compound, and is adjusted for unit type, finishing, delivery date and size.": "تبدأ كل وحدة من منطقتها، ثم مطوّرها، ثم الكمبوند، وتُعدَّل حسب نوع الوحدة والتشطيب وموعد التسليم والمساحة.",
  "Egypt publishes no resale transaction prices. A fair value is where comparable asking prices sit once payment plans are converted to cash, and final deals are often lower.": "لا تُنشر في مصر أسعار صفقات إعادة البيع. القيمة العادلة هي موقع الأسعار المطلوبة للوحدات المماثلة بعد تحويل خطط السداد إلى كاش، وكثيرًا ما تُغلق الصفقات بأقل من ذلك.",
  "Egypt-wide {class}": "{class} على مستوى مصر",
  "Enter an area between 20 and 5,000 m².": "أدخل مساحة بين ٢٠ و٥٬٠٠٠ م².",
  "Enter how many years of installments remain.": "أدخل عدد سنوات الأقساط المتبقية.",
  "Enter the full headline price in EGP.": "أدخل السعر المُعلن كاملًا بالجنيه.",
  "Evaluate": "قيّم",
  "Evaluate a unit": "قيّم وحدة",
  "Every fair value on Qayem comes from one published model, checked against units it has not seen. Here is the model, its accuracy, and what it cannot know.": "كل قيمة عادلة على قيّم تأتي من نموذج واحد منشور، مُختبر على وحدات لم يرها. هنا النموذج ودقته وما لا يمكنه معرفته.",
  "Every re-crawl compares each unit’s promised handover date with the last one we saw. A pattern of postponements is a risk signal that marketing never shows.": "في كل جولة جمع نقارن موعد التسليم الموعود لكل وحدة بآخر موعد رأيناه. تكرار التأجيل إشارة خطر لا تُظهرها الإعلانات أبدًا.",
  "Every resale unit,": "كل وحدة إعادة بيع،",
  "Every value carries an evidence grade and a range measured on held-out units. When the evidence is thin, we say so instead of guessing.": "كل قيمة تحمل درجة دليل ونطاقًا مقيسًا على وحدات مُستبعدة من التدريب. وحين يكون الدليل ضعيفًا نقول ذلك بدل التخمين.",
  "Evidence": "الدليل",
  "Fair cash / m²": "القيمة العادلة كاش / م²",
  "Fair cash value per m² for each compound, and how far it sits above or below comparable units in its district.": "القيمة العادلة كاش للمتر في كل كمبوند، ومدى ارتفاعها أو انخفاضها عن الوحدات المماثلة في منطقتها.",
  "Fair cash value, finished and ready, typical size": "القيمة العادلة كاش، متشطبة واستلام فوري، بمساحة معتادة",
  "Fair range": "النطاق العادل",
  "Fair range {low} to {high}; central estimate {fair}.": "النطاق العادل من {low} إلى {high}؛ التقدير المركزي {fair}.",
  "Fair value": "القيمة العادلة",
  "Fair value plus the same fees": "القيمة العادلة مع الرسوم نفسها",
  "Fair values are estimates built from published asking prices, not appraisals or completed sales. Confirm every detail with the seller and the developer.": "القيم العادلة تقديرات مبنية على أسعار مطلوبة منشورة، وليست تقييمات رسمية أو صفقات مكتملة. تحقّق من كل التفاصيل مع البائع والمطوّر.",
  "Family House": "بيت عائلة",
  "Fees differ by developer and deal. These are editable assumptions, as a share of the headline price.": "تختلف الرسوم حسب المطوّر والصفقة. هذه افتراضات قابلة للتعديل كنسبة من السعر المُعلن.",
  "Find this listing": "ابحث عن هذا الإعلان",
  "Finished": "متشطب",
  "Finishing": "التشطيب",
  "Finishing mix": "توزيع التشطيب",
  "Floor, view and orientation": "الدور والإطلالة والاتجاه",
  "Footer": "تذييل الصفحة",
  "Furnished": "مفروش",
  "Furthest below fair value first": "الأبعد تحت القيمة العادلة أولًا",
  "Go to": "انتقل إلى",
  "Headline above cash value by": "السعر المُعلن أعلى من قيمة الكاش بـ",
  "Headline price": "السعر المُعلن",
  "Headline price (EGP)": "السعر المُعلن (ج.م)",
  "Held-out accuracy": "الدقة على وحدات مُستبعدة",
  "Highest and lowest": "الأعلى والأدنى",
  "Highest premium": "أعلى علاوة",
  "History is still short": "السجل ما زال قصيرًا",
  "House": "منزل",
  "How a fair value": "كيف تُبنى القيمة العادلة",
  "How a unit is valued": "كيف تُقيَّم الوحدة",
  "How each developer’s resale units price against comparable units in the same districts, and what their stock looks like: delivery, payment plans and finishing.": "كيف تُسعَّر وحدات إعادة البيع لكل مطوّر مقابل الوحدات المماثلة في المناطق نفسها، وشكل المعروض لديه: التسليم وخطط السداد والتشطيب.",
  "How the fair value was built": "كيف بُنيت القيمة العادلة",
  "How to evaluate": "طريقة التقييم",
  "Identified resale": "إعادة بيع مؤكدة",
  "Identified resale listings with their cash-equivalent price, Qayem’s fair range and the strength of the evidence behind it.": "إعلانات إعادة البيع المؤكدة بسعرها المكافئ للكاش، والنطاق العادل من قيّم، وقوة الدليل وراءه.",
  "If a broker is involved": "إن كان هناك سمسار",
  "In 1–2 years": "خلال ١–٢ سنة",
  "In 2–3 years": "خلال ٢–٣ سنوات",
  "In 3+ years": "بعد ٣ سنوات أو أكثر",
  "In Egypt the developer and the compound set the price per m² as much as the neighbourhood does. Here is how each developer’s resale units price against comparable units in the same districts.": "في مصر يحدد المطوّر والكمبوند سعر المتر بقدر ما تحدده المنطقة. هكذا تُسعَّر وحدات إعادة البيع لكل مطوّر مقابل الوحدات المماثلة في المناطق نفسها.",
  "In comparison": "في الميزان",
  "In the listing’s own words": "بكلمات الإعلان نفسه",
  "In {n} years": "بعد {n} سنة",
  "In {year}": "في {year}",
  "Included: active sale listings in EGP between EGP 100,000 and 200 million, 20–5,000 m², with a property type and a district or compound. Only identified resale listings are valued by default. A complete run covers its defined scope, not the whole market.": "المشمول: إعلانات بيع نشطة بالجنيه بين ١٠٠ ألف و٢٠٠ مليون جنيه، بمساحة ٢٠–٥٬٠٠٠ م²، مع نوع عقار ومنطقة أو كمبوند. تُقيَّم افتراضيًا إعلانات إعادة البيع المؤكدة فقط. دورة الجمع المكتملة تغطي نطاقها المحدد، لا السوق كله.",
  "Indexed records": "السجلات المفهرسة",
  "Indexed records, resale listings and valued listings by source": "السجلات المفهرسة وإعلانات إعادة البيع والإعلانات المُقيَّمة حسب المصدر",
  "Installment plan": "خطة تقسيط",
  "Installment plans with known terms": "خطط تقسيط معروفة الشروط",
  "Installment term": "مدة التقسيط",
  "Installments": "تقسيط",
  "Installments, term not published": "تقسيط، والمدة غير منشورة",
  "Is this": "هل هذا",
  "Its compounds": "كمبونداته",
  "Kept in this browser only. No account, no enquiries sent to anyone.": "محفوظة في هذا المتصفح فقط. بلا حساب، ولا تُرسل أي استفسارات لأحد.",
  "Know the evidence": "اعرف الدليل",
  "Land": "أرض",
  "Last observed": "آخر رصد",
  "Latest promised delivery": "آخر موعد تسليم موعود",
  "Legal status": "الوضع القانوني",
  "Let’s try that again": "لنحاول مرة أخرى",
  "Likely range {low} – {high}": "النطاق المرجّح {low} – {high}",
  "Limits": "الحدود",
  "Listed on installment plans": "معروضة بخطط تقسيط",
  "Listing link": "رابط الإعلان",
  "Listings": "الإعلانات",
  "Listings, not unique units": "إعلانات، لا وحدات فريدة",
  "Localbusiness": "نشاط تجاري",
  "Loft": "لوفت",
  "Lowest premium": "أدنى علاوة",
  "Main class": "الفئة الرئيسية",
  "Main navigation": "القائمة الرئيسية",
  "Main source": "المصدر الرئيسي",
  "Maintenance deposit": "وديعة الصيانة",
  "Maintenance deposit status": "حالة وديعة الصيانة",
  "Measure": "المقياس",
  "Median asking / m²": "وسيط السعر المطلوب / م²",
  "Median cash-equivalent / m²": "وسيط المكافئ النقدي / م²",
  "Median error": "الخطأ الوسيط",
  "Median error on held-out units": "الخطأ الوسيط على وحدات مُستبعدة",
  "Median error on the same units": "الخطأ الوسيط على الوحدات نفسها",
  "Median error on the same {n} units": "الخطأ الوسيط على الوحدات نفسها ({n})",
  "Median gap between each unit’s cash-equivalent asking price and the value predicted without it, across {n} units.": "الفجوة الوسيطة بين السعر المطلوب المكافئ للكاش لكل وحدة والقيمة المتوقعة من دونها، عبر {n} وحدة.",
  "Median plan length": "المدة الوسيطة للخطة",
  "Median share still owed": "النسبة الوسيطة المتبقية للسداد",
  "Median wait for the rest": "الانتظار الوسيط لغير الجاهز",
  "Methodology": "المنهجية",
  "Model trained on": "دُرّب النموذج على",
  "Most identified resale listings come from one source. Figures describe the listings we index, not the whole Egyptian market.": "معظم إعلانات إعادة البيع المؤكدة تأتي من مصدر واحد. الأرقام تصف الإعلانات التي نفهرسها، لا السوق المصري كله.",
  "Most listings": "الأكثر إعلانات",
  "Name": "الاسم",
  "Next page": "الصفحة التالية",
  "No compound": "بلا كمبوند",
  "No compounds match.": "لا توجد كمبوندات مطابقة.",
  "No developers match.": "لا يوجد مطورون مطابقون.",
  "No units match.": "لا توجد وحدات مطابقة.",
  "Not available": "غير متاح",
  "Not enough evidence to value this unit.": "لا يوجد دليل كافٍ لتقييم هذه الوحدة.",
  "Not enough valued units yet": "لا توجد وحدات مُقيَّمة كافية بعد",
  "Not graded": "بلا درجة",
  "Not positioned": "غير محدد الموقع",
  "Not provided": "غير متوفر",
  "Not published": "غير منشور",
  "Not recorded": "غير مسجّل",
  "Not sure": "لست متأكدًا",
  "Not valued": "غير مُقيَّمة",
  "Nothing matches that yet.": "لا شيء يطابق ذلك بعد.",
  "Nothing on your watchlist yet.": "قائمة المتابعة فارغة.",
  "Nothing to compare yet.": "لا شيء للمقارنة بعد.",
  "Observation window": "فترة الرصد",
  "Off the map": "خارج الخريطة",
  "Office": "مكتب",
  "Often due at handover if the seller has not paid it": "غالبًا تُستحق عند الاستلام إن لم يدفعها البائع",
  "On plans": "بالتقسيط",
  "On this payment plan, a fair headline price would be about {fair} (listed at {price}).": "بهذه الخطة يكون السعر المُعلن العادل نحو {fair} (المعروض {price}).",
  "Only if you register the title": "فقط إن سجّلت الملكية",
  "Open a compound or developer and choose Compare.": "افتح كمبوندًا أو مطوّرًا واختر «قارن».",
  "Open a compound or developer and choose Watch.": "افتح كمبوندًا أو مطوّرًا واختر «تابِع».",
  "Or paste a listing link": "أو الصق رابط إعلان",
  "Other": "أخرى",
  "Over": "على مدى",
  "Overpayment plus the down payment already paid to the developer": "الأوفر مضافًا إليه المقدم المدفوع بالفعل للمطوّر",
  "Pages": "الصفحات",
  "Paid at signing": "المدفوع عند التعاقد",
  "Paid at signing (EGP)": "المدفوع عند التعاقد (ج.م)",
  "Paid later": "يُدفع لاحقًا",
  "Partial run": "دورة جمع جزئية",
  "Paste a listing link": "الصق رابط إعلان",
  "Payment": "السداد",
  "Payment terms": "شروط السداد",
  "Payment terms not published": "شروط السداد غير منشورة",
  "Penthouse": "بنتهاوس",
  "Plan discount": "خصم الخطة",
  "Plan, term unknown": "تقسيط، المدة غير معروفة",
  "Position": "الموقع",
  "Positioned against fair value": "محدد الموقع مقابل القيمة العادلة",
  "Preferences": "التفضيلات",
  "Premium against each district": "العلاوة مقابل كل منطقة",
  "Premium vs district": "العلاوة مقابل المنطقة",
  "Premium vs district norm": "العلاوة مقابل متوسط المنطقة",
  "Previous page": "الصفحة السابقة",
  "Price per m² is modelled in cash-equivalent terms. Each unit starts from its property class across Egypt, then moves towards its district, its developer within that district, and its compound, each by as much as the number of listings there justifies.": "يُنمذج سعر المتر بالمكافئ النقدي. تبدأ كل وحدة من فئتها على مستوى مصر، ثم تتجه نحو منطقتها، ثم مطوّرها داخل المنطقة، ثم الكمبوند، كلٌّ بقدر ما يبرره عدد الإعلانات هناك.",
  "Price per m² when the area doubles": "سعر المتر عند مضاعفة المساحة",
  "Price the compound, not the map": "سعّر الكمبوند، لا الخريطة",
  "Price trends, time on market and delivery postponements need repeated observation. They appear once there are eight weeks of history.": "اتجاهات الأسعار ومدة البقاء في السوق وتأجيلات التسليم تحتاج رصدًا متكررًا. تظهر بعد ثمانية أسابيع من السجل.",
  "Price trends, time on market and delivery-date changes appear after eight weeks of observation. Qayem has observed this market for {n} days.": "تظهر اتجاهات الأسعار ومدة البقاء في السوق وتغيّر مواعيد التسليم بعد ثمانية أسابيع من الرصد. رصد قيّم هذا السوق منذ {n} يوم.",
  "Priced against its district": "مُسعَّر مقابل منطقته",
  "Priced below / within / above range": "أقل من / ضمن / أعلى من النطاق",
  "Prices are what sellers ask, not what buyers paid. Egypt publishes no resale transaction prices, so a fair value is where comparable asking prices sit.": "الأسعار هي ما يطلبه البائعون، لا ما دفعه المشترون. لا تُنشر في مصر أسعار صفقات إعادة البيع، فالقيمة العادلة هي موقع الأسعار المطلوبة للوحدات المماثلة.",
  "Promised dates, tracked": "المواعيد الموعودة، تحت المتابعة",
  "Property types": "أنواع العقارات",
  "Qayem": "قيّم",
  "Qayem fair value · cash today": "القيمة العادلة من قيّم، كاش اليوم",
  "Qayem has observed this market for {n} days.": "رصد قيّم هذا السوق منذ {n} يوم.",
  "Qayem home": "الصفحة الرئيسية لقيّم",
  "Qayem model": "نموذج قيّم",
  "Qayem values Egypt’s resale units by compound, developer, delivery date and payment plan, not by area alone, and tells you how sure it is.": "يقيّم قيّم وحدات إعادة البيع في مصر حسب الكمبوند والمطوّر وموعد التسليم وخطة السداد، لا بالمساحة وحدها، ويخبرك بمدى ثقته.",
  "Qayem weighs Egypt's resale property market: every listing scored, sourced, and priced against its peers.": "قيّم يقدّر القيمة العادلة لوحدات إعادة البيع في مصر حسب الكمبوند والمطوّر والتسليم وخطة السداد.",
  "Quick navigation": "تنقّل سريع",
  "Read full description": "اقرأ الوصف كاملًا",
  "Read the methodology": "اقرأ المنهجية",
  "Ready": "استلام فوري",
  "Ready now": "استلام فوري",
  "Ready to move in": "جاهزة للسكن",
  "Registration": "التسجيل",
  "Registration and contract status": "التسجيل ونوع العقد",
  "Registration, contract type and outstanding dues are not published. Confirm them with the developer before paying anything.": "التسجيل ونوع العقد والمستحقات المتأخرة غير منشورة. تأكد منها مع المطوّر قبل دفع أي مبلغ.",
  "Remove {name} from comparison": "إزالة {name} من المقارنة",
  "Remove {name} from your watchlist": "إزالة {name} من قائمة المتابعة",
  "Removed from comparison": "أُزيل من المقارنة",
  "Removed from your watchlist": "أُزيل من قائمة المتابعة",
  "Resale evidence": "دليل إعادة البيع",
  "Resale fair value": "القيمة العادلة لإعادة البيع",
  "Resale fair-value index": "مؤشر القيمة العادلة لإعادة البيع",
  "Resale listings": "إعلانات إعادة البيع",
  "Resale status unclassified": "حالة إعادة البيع غير مصنّفة",
  "Resale units": "وحدات إعادة البيع",
  "Resale units valued": "وحدات إعادة بيع مُقيَّمة",
  "Resale, with its evidence": "إعادة بيع، بدليلها",
  "Roof": "روف",
  "Class: {cls}. Nearest in size, from the same compound where possible.": "الفئة: {cls}. الأقرب مساحةً، ومن الكمبوند نفسه متى أمكن.",
  "Same district.": "المنطقة نفسها.",
  "Say how sure we are": "نقول مدى ثقتنا",
  "Search": "ابحث",
  "Search Qayem": "ابحث في قيّم",
  "Search compounds": "ابحث في الكمبوندات",
  "Search developers": "ابحث في المطورين",
  "Search units": "ابحث في الوحدات",
  "See its units": "اعرض وحداته",
  "See source coverage": "اطّلع على تغطية المصادر",
  "See the accuracy": "اطّلع على الدقة",
  "Semi Finished": "نصف تشطيب",
  "Shop": "محل",
  "Show less": "عرض أقل",
  "Side by side,": "جنبًا إلى جنب،",
  "Size": "المساحة",
  "Sizes from {min} to {max} m²": "مساحات من {min} إلى {max} م²",
  "Skip to content": "تخطَّ إلى المحتوى",
  "Sort by": "رتّب حسب",
  "Source": "المصدر",
  "Sources rarely publish them, so they are not in the model. A sea-view or garden unit can be worth well above its compound’s norm.": "نادرًا ما تنشرها المصادر، لذا ليست في النموذج. قد تساوي وحدة بإطلالة بحر أو بحديقة أكثر بكثير من متوسط الكمبوند.",
  "Start typing a compound name": "ابدأ بكتابة اسم الكمبوند",
  "Still owed": "المتبقي للسداد",
  "Stock on the resale market": "المعروض في سوق إعادة البيع",
  "Studio": "استوديو",
  "Switch to English": "Switch to English",
  "Terms unknown": "الشروط غير معروفة",
  "Tested on units": "مُختبر على وحدات",
  "That page isn’t here.": "هذه الصفحة غير موجودة.",
  "The amount paid at signing must be between 0 and the headline price.": "يجب أن يكون المدفوع عند التعاقد بين صفر والسعر المُعلن.",
  "The compound": "الكمبوند",
  "The compounds": "الكمبوندات",
  "The evidence": "الدليل",
  "The model": "النموذج",
  "The name on the gate": "الاسم على البوابة",
  "The payment plan, in today’s money": "خطة السداد بقيمة اليوم",
  "The price": "السعر",
  "The resale signal comes from a source field, a dedicated resale catalogue, or a keyword. It is shown on every unit.": "إشارة إعادة البيع مصدرها حقل في المصدر أو كتالوج مخصص لإعادة البيع أو كلمة مفتاحية، وتظهر على كل وحدة.",
  "The same unit can appear on several platforms or be listed twice by different brokers. Counts are listings.": "قد تظهر الوحدة نفسها على عدة منصات أو يعرضها سمساران مختلفان. الأعداد أعداد إعلانات.",
  "The unit": "الوحدة",
  "This page is not available.": "هذه الصفحة غير متاحة.",
  "Three steps,": "ثلاث خطوات،",
  "Too little evidence, or not a residential unit. We do not guess.": "دليل غير كافٍ، أو ليست وحدة سكنية. نحن لا نخمّن.",
  "Total cost of buying": "التكلفة الإجمالية للشراء",
  "Townhouse": "تاون هاوس",
  "Transfer fees and deposits": "رسوم التنازل والودائع",
  "Try a different name or district.": "جرّب اسمًا أو منطقة مختلفة.",
  "Try a different name.": "جرّب اسمًا مختلفًا.",
  "Try again": "حاول مرة أخرى",
  "Try fewer filters or a broader search.": "جرّب عوامل تصفية أقل أو بحثًا أوسع.",
  "Twinhouse": "توين هاوس",
  "Typical valuation error": "خطأ التقييم المعتاد",
  "Unavailable · retry": "غير متاح، أعد المحاولة",
  "Under 1 Year": "خلال سنة",
  "Unit": "الوحدة",
  "Unit type": "نوع الوحدة",
  "Unit valuation": "تقييم الوحدة",
  "Units": "الوحدات",
  "Units in this compound": "الوحدات في هذا الكمبوند",
  "Units matching “{q}”": "وحدات تطابق «{q}»",
  "Units tested": "الوحدات المختبرة",
  "Units with a promised delivery date": "وحدات لها موعد تسليم موعود",
  "Units with their fair-value range": "الوحدات مع نطاق قيمتها العادلة",
  "Unknown": "غير معروف",
  "Valuation": "التقييم",
  "Value a unit": "قيّم وحدة",
  "Value a unit here": "قيّم وحدة هنا",
  "Value this unit": "قيّم هذه الوحدة",
  "Valued": "مُقيَّمة",
  "Valuing the unit…": "جارٍ تقييم الوحدة…",
  "View on {source}": "اعرض على {source}",
  "Villa": "فيلا",
  "Villas & houses": "فيلات ومنازل",
  "Vs district": "مقابل المنطقة",
  "Vs district is the average gap between the developer’s units and the benchmark for the same class in the same district, after adjusting for unit type, finishing, delivery and size. It needs at least five valued units, and twenty to appear in a premium ranking.": "«مقابل المنطقة» هو متوسط الفجوة بين وحدات المطوّر ومرجع الفئة نفسها في المنطقة نفسها، بعد التعديل حسب نوع الوحدة والتشطيب والتسليم والمساحة. يحتاج خمس وحدات مُقيَّمة على الأقل، وعشرين للظهور في ترتيب العلاوات.",
  "Warehouse": "مخزن",
  "Watch": "تابِع",
  "Watching": "قيد المتابعة",
  "Watchlist": "قائمة المتابعة",
  "We could not load the data. Please try again.": "تعذّر تحميل البيانات. حاول مرة أخرى.",
  "We do not recognise that developer.": "لا نعرف هذا المطوّر.",
  "We have no resale listings for that compound, so it is valued at district level.": "ليس لدينا إعلانات إعادة بيع لهذا الكمبوند، لذا يُقيَّم على مستوى المنطقة.",
  "We have no resale listings in that district.": "ليس لدينا إعلانات إعادة بيع في هذه المنطقة.",
  "We have not indexed that listing link. Enter its details instead.": "لم نفهرس رابط هذا الإعلان. أدخل تفاصيله بدلًا من ذلك.",
  "Weighing the market…": "جارٍ وزن السوق…",
  "What a fair value": "ما لا يمكن",
  "What is it": "كم تساوي",
  "What its resale stock looks like": "كيف يبدو معروضه لإعادة البيع",
  "What this is built on,": "على ماذا بُني هذا،",
  "What this valuation cannot see": "ما لا يراه هذا التقييم",
  "What was paid at signing counts in full. The balance is spread over the remaining term in quarterly installments and discounted at {rate} a year, roughly what the same money earns in Egyptian deposits.": "المدفوع عند التعاقد يُحتسب كاملًا. يُوزَّع الباقي على المدة المتبقية بأقساط ربع سنوية ويُخصم بمعدل {rate} سنويًا، وهو تقريبًا ما يكسبه المبلغ نفسه في الودائع المصرية.",
  "What you are really buying": "ما الذي تشتريه فعلًا",
  "Where": "المكان",
  "Where the evidence": "من أين يأتي",
  "Which compound is the unit in?": "في أي كمبوند الوحدة؟",
  "Why area alone misleads": "لماذا تضلّل المساحة وحدها",
  "Within a year": "خلال سنة",
  "Within fair range": "ضمن النطاق العادل",
  "Within ±10%": "ضمن ±١٠٪",
  "Within ±20%": "ضمن ±٢٠٪",
  "Worth today": "قيمتها اليوم",
  "Years of installments left": "سنوات الأقساط المتبقية",
  "You can compare up to 3. Remove one to add another.": "يمكنك مقارنة ٣ على الأكثر. أزل واحدًا لإضافة آخر.",
  "You will see a fair cash value with a likely range, what the payment plan is worth today, how the value was built, and the comparable listings behind it.": "سترى قيمة عادلة كاش مع نطاق مرجّح، وقيمة خطة السداد اليوم، وكيف بُنيت القيمة، والإعلانات المماثلة وراءها.",
  "Your selection will last for this visit only. Browser storage is unavailable.": "سيبقى اختيارك لهذه الزيارة فقط؛ تخزين المتصفح غير متاح.",
  "Your valuation appears here": "يظهر تقييمك هنا",
  "Your watchlist holds up to 100 entries.": "تتسع قائمة المتابعة لـ١٠٠ عنصر.",
  "a fair price?": "سعرًا عادلًا؟",
  "cannot tell you.": "للقيمة العادلة أن تخبرك به.",
  "comes from.": "الدليل.",
  "every unit.": "لكل وحدة.",
  "fair cash / m²": "القيمة العادلة كاش / م²",
  "fees {share}": "الرسوم {share}",
  "is built, and tested.": "وكيف تُختبر.",
  "is not a cash price.": "ليس سعرًا كاش.",
  "is priced in.": "له ثمن.",
  "it has not seen.": "لم يرها.",
  "like for like.": "بالمثل.",
  "loading…": "جارٍ التحميل…",
  "m²": "م²",
  "observed {date}": "رُصد {date}",
  "plainly.": "بوضوح.",
  "really worth?": "فعلًا؟",
  "sets the price.": "يحدد السعر.",
  "then the unit.": "ثم الوحدة.",
  "to move": "للتنقل",
  "to open": "للفتح",
  "valued.": "مُقيَّمة.",
  "vs district": "مقابل المنطقة",
  "you care about.": "التي تهمّك.",
  "{developer}: {premium} vs district across {n} listings": "{developer}: {premium} مقابل المنطقة عبر {n} إعلان",
  "{label} compound": "كمبوند {label}",
  "{label} district": "منطقة {label}",
  "{label} in this district": "{label} في هذه المنطقة",
  "{n} bed": "غرفة واحدة",
  "{n} beds": "{n} غرف",
  "{n} compounds": "{n} كمبوند",
  "{n} districts": "{n} منطقة",
  "{n} further compounds have too few listings for a premium.": "{n} كمبوند آخر إعلاناته أقل من أن تُحسب له علاوة.",
  "{n} listings": "{n} إعلان",
  "{n} listings · {change}": "{n} إعلان، {change}",
  "{n} m² vs typical {typical} m²": "{n} م² مقابل {typical} م² معتادة",
  "{n} sources": "{n} مصادر",
  "{n} units": "{n} وحدة",
  "{n} years": "{n} سنة",
  "{n}-year plan": "خطة {n} سنة",
  "{premium} against comparable units in {district}": "{premium} مقابل الوحدات المماثلة في {district}",
  "{share} from {source}": "{share} من {source}",
  "{start}–{end} of {total} compounds": "{start}–{end} من {total} كمبوند",
  "{start}–{end} of {total} developers": "{start}–{end} من {total} مطوّر",
  "{start}–{end} of {total} units": "{start}–{end} من {total} وحدة",
  "Payment plan": "خطة السداد",
  "Cash-equivalent price against a cash unit": "السعر المكافئ للكاش مقارنةً بوحدة كاش",
  "Under 3 years left": "أقل من ٣ سنوات متبقية",
  "3–6 years left": "٣–٦ سنوات متبقية",
  "6–9 years left": "٦–٩ سنوات متبقية",
  "9+ years left": "٩ سنوات فأكثر متبقية",
  "Term not published": "المدة غير منشورة",
  "For the median installment listing the cash value is {cut} below the headline. When terms are not fully published the unit is valued but its price is not positioned: classified listings often show only what is due now.": "في إعلان التقسيط الوسيط تقل القيمة كاش عن السعر المُعلن بنسبة {cut}. حين لا تُنشر الشروط كاملة تُقيَّم الوحدة دون تحديد موقع سعرها، فإعلانات المبوبة كثيرًا ما تعرض المستحق الآن فقط.",
  "These effects are fitted from the data, not assumed. The payment-plan effect shows how buyers actually price long plans: less steeply than a flat discount rate. Listings more than 2.5× away from their district norm are excluded from fitting and flagged “check this listing”.": "هذه التأثيرات مقدَّرة من البيانات لا مفترضة. يُظهر تأثير خطة السداد كيف يسعّر المشترون الخطط الطويلة فعلًا: بخصم أخف من معدل ثابت. الإعلانات التي تبعد أكثر من ٢٫٥ ضعف عن متوسط منطقتها تُستبعد من التقدير وتُعلَّم «راجع هذا الإعلان».",
  "The payment terms were not fully published, so the asking price is not placed against the range. Classified listings often show only what is due now, not the remaining installments.": "لم تُنشر شروط السداد كاملة، لذا لا يُحدَّد موقع السعر المطلوب من النطاق. إعلانات المبوبة كثيرًا ما تعرض المستحق الآن فقط، لا الأقساط المتبقية.",
  "Too few comparable listings outside compounds in this district.": "إعلانات مماثلة خارج الكمبوندات في هذه المنطقة أقل من اللازم.",
  "Too few comparable listings in this district and class.": "إعلانات مماثلة من هذه الفئة في هذه المنطقة أقل من اللازم.",
  "Qayem values apartments, chalets and houses only.": "يقيّم قيّم الشقق والشاليهات والمنازل فقط.",
  "Choose a known compound or district.": "اختر كمبوندًا أو منطقة معروفة.",
  "This unit is unavailable or does not meet the published inclusion rules.": "هذه الوحدة غير متاحة أو لا تستوفي قواعد الإدراج المنشورة.",
  "Choose a compound or a district.": "اختر كمبوندًا أو منطقة.",
  "The down payment cannot exceed the total price.": "لا يمكن أن يتجاوز المدفوع عند التعاقد السعر الإجمالي.",
  "We have no identified resale listings for this compound.": "ليس لدينا إعلانات إعادة بيع مؤكدة لهذا الكمبوند.",
  "We have no identified resale listings for this developer.": "ليس لدينا إعلانات إعادة بيع مؤكدة لهذا المطوّر.",
  "We have no identified resale listings for this district.": "ليس لدينا إعلانات إعادة بيع مؤكدة في هذه المنطقة.",
  "Qayem dataset is unavailable. Set QAYEM_DB to an existing Qayem database.": "بيانات قيّم غير متاحة حاليًا.",
  "Price trends, time on market and delivery-date changes appear after eight weeks of observation. Qayem has observed this market for {n} day.": "تظهر اتجاهات الأسعار ومدة البقاء في السوق وتغيّر مواعيد التسليم بعد ثمانية أسابيع من الرصد. رصد قيّم هذا السوق منذ يوم واحد.",
  "Qayem has observed this market for {n} day.": "رصد قيّم هذا السوق منذ يوم واحد.",
  "No current developer launch units could be matched to this compound.": "لم نتمكن من مطابقة وحدات إطلاق حالية من المطوّر مع هذا الكمبوند.",
  "No current launch units from this developer could be matched to a resale compound.": "لم نتمكن من مطابقة وحدات إطلاق حالية لهذا المطوّر مع كمبوند في سوق إعادة البيع.",
  "Buying new from the developer costs this much more than the resale market pays for the same unit, in today’s money.": "الشراء الجديد من المطوّر أغلى بهذه النسبة مما يدفعه سوق إعادة البيع في الوحدة نفسها، بقيمة اليوم.",
  "Buying new from the developer costs this much less than the resale market pays for the same unit, in today’s money.": "الشراء الجديد من المطوّر أرخص بهذه النسبة مما يدفعه سوق إعادة البيع في الوحدة نفسها، بقيمة اليوم.",
  "Launch headline / m²": "سعر الإطلاق المُعلن / م²",
  "Launch cash-equivalent / m²": "المكافئ النقدي لسعر الإطلاق / م²",
  "Typical launch plan": "خطة الإطلاق المعتادة",
  "{down} down, {n} years": "مقدم {down}، على {n} سنة",
  "Latest launch delivery": "آخر موعد تسليم للإطلاق",
  "Launch units compared": "وحدات الإطلاق المقارنة",
  "Phases": "المراحل",
  "Launch units are priced against the model’s resale value for the same compound, unit type, finishing, delivery date, plan length and size. Launch prices are list prices; negotiated developer discounts are not visible.": "تُقارن وحدات الإطلاق بقيمة النموذج لإعادة البيع للكمبوند ونوع الوحدة والتشطيب وموعد التسليم ومدة الخطة والمساحة نفسها. أسعار الإطلاق أسعار قوائم، ولا تظهر خصومات المطوّر المتفاوض عليها.",
  "Resale vs buying new": "إعادة البيع مقابل الشراء الجديد",
  "Against the developer’s launch price": "مقارنةً بسعر إطلاق المطوّر",
  "Against the developer’s launch prices": "مقارنةً بأسعار إطلاق المطوّر",
  "Vs launch": "مقابل الإطلاق",
  "Fair cash / m² is for a finished, ready unit of typical size in the compound’s most listed class. Vs district compares it with the district’s own benchmark for the same class. Plan discount is how far the median installment headline sits above its value in today’s money.": "القيمة العادلة كاش / م² لوحدة متشطبة استلام فوري بمساحة معتادة من الفئة الأكثر عرضًا في الكمبوند. «مقابل المنطقة» يقارنها بمرجع المنطقة للفئة نفسها. «خصم الخطة» هو مقدار ارتفاع السعر المُعلن الوسيط للتقسيط عن قيمته اليوم.",
  "Vs launch is how far the developer’s current launch price sits above what the resale market pays for the same unit.": "«مقابل الإطلاق» هو مقدار ارتفاع سعر إطلاق المطوّر الحالي عما يدفعه سوق إعادة البيع في الوحدة نفسها.",
  "Launch prices are list prices": "أسعار الإطلاق أسعار قوائم",
  "Developer launch prices come from the developers’ own current listings on Nawy. Negotiated discounts and private offers are not visible.": "تأتي أسعار إطلاق المطورين من إعلاناتهم الحالية على ناوي. لا تظهر الخصومات المتفاوض عليها والعروض الخاصة.",
  "{n} current developer launch units in {c} compounds are compared with the model’s resale value for the same unit on the same plan. The median launch unit costs {spread} against resale, in today’s money.": "قورنت {n} وحدة إطلاق حالية في {c} كمبوند بقيمة النموذج لإعادة البيع للوحدة نفسها بالخطة نفسها. وحدة الإطلاق الوسيطة تكلّف {spread} مقارنةً بإعادة البيع، بقيمة اليوم.",
  "Nawy (developer launches)": "ناوي (إطلاقات المطورين)",
  "Contract and receipts verified by AqarExit": "العقد والإيصالات متحقق منها بواسطة عقار إكزت",
  "Launch plans are long and back-loaded, so the comparison depends on how the model prices such plans. {n} resale units carry launch-like plans (85% or more still owed, seven or more years); the model values them with a median bias of {bias}.": "خطط الإطلاق طويلة ومؤجلة السداد، لذا تعتمد المقارنة على كيفية تسعير النموذج لمثل هذه الخطط. تحمل {n} وحدة إعادة بيع خططًا شبيهة بالإطلاق (٨٥٪ أو أكثر متبقٍ، وسبع سنوات أو أكثر)، ويقيّمها النموذج بانحياز وسيط قدره {bias}.",
  "The listing says «{word}» (resale).": "يذكر الإعلان «{word}» (إعادة بيع).",
  "Listed in Nawy’s resale section.": "معروضة في قسم إعادة البيع على ناوي.",
  "A contract transfer (تنازل). AqarExit verified the contract and receipts.": "تنازل عن عقد، وتحققت عقار إكزت من العقد والإيصالات.",
  "Listed on a contract-transfer (تنازل) marketplace.": "معروضة على منصة للتنازل عن العقود.",
  "The listing says «تمليك» (freehold), wording used for resale.": "يذكر الإعلان «تمليك»، وهي صيغة تُستخدم في إعادة البيع.",
  "Listed in GPM’s resale catalogue.": "معروضة في كتالوج إعادة البيع لدى GPM.",
  "Sold directly by the owner.": "يبيعها المالك مباشرة.",
  "Aqarmap marks it as a resale on installments.": "يصنّفها عقارماب إعادة بيع بالتقسيط.",
  "The listing description says it is a resale.": "يذكر وصف الإعلان أنها إعادة بيع.",
  "{n} listings|one": "إعلان واحد",
  "{n} listings|two": "إعلانان",
  "{n} listings|few": "{n} إعلانات",
  "{n} listings · {change}|one": "إعلان واحد، {change}",
  "{n} listings · {change}|two": "إعلانان، {change}",
  "{n} listings · {change}|few": "{n} إعلانات، {change}",
  "{n} units|one": "وحدة واحدة",
  "{n} units|two": "وحدتان",
  "{n} units|few": "{n} وحدات",
  "{n} compounds|one": "كمبوند واحد",
  "{n} compounds|two": "كمبوندان",
  "{n} compounds|few": "{n} كمبوندات",
  "{n} districts|one": "منطقة واحدة",
  "{n} districts|two": "منطقتان",
  "{n} districts|few": "{n} مناطق",
  "{n} sources|two": "مصدران",
  "{n} years|one": "سنة واحدة",
  "{n} years|two": "سنتان",
  "{n} years|few": "{n} سنوات",
  "{n} beds|two": "غرفتان",
  "{n} beds|many": "{n} غرفة",
  "Qayem has observed this market for {n} days.|one": "رصد قيّم هذا السوق منذ يوم واحد.",
  "Qayem has observed this market for {n} days.|two": "رصد قيّم هذا السوق منذ يومين.",
  "Qayem has observed this market for {n} days.|few": "رصد قيّم هذا السوق منذ {n} أيام.",
  "Qayem has observed this market for {n} days.|many": "رصد قيّم هذا السوق منذ {n} يومًا.",
  "Price trends, time on market and delivery-date changes appear after eight weeks of observation. Qayem has observed this market for {n} days.|few": "تظهر اتجاهات الأسعار ومدة البقاء في السوق وتغيّر مواعيد التسليم بعد ثمانية أسابيع من الرصد. رصد قيّم هذا السوق منذ {n} أيام.",
  "Price trends, time on market and delivery-date changes appear after eight weeks of observation. Qayem has observed this market for {n} days.|many": "تظهر اتجاهات الأسعار ومدة البقاء في السوق وتغيّر مواعيد التسليم بعد ثمانية أسابيع من الرصد. رصد قيّم هذا السوق منذ {n} يومًا.",
  "Days of observation so far. Price trends, time on market and delivery delays are shown only once there are at least eight weeks of history.|few": "أيام من الرصد حتى الآن. لا تظهر اتجاهات الأسعار ومدة البقاء في السوق وتأخيرات التسليم إلا بعد ثمانية أسابيع على الأقل من السجل.",
  "Days of observation so far. Price trends, time on market and delivery delays are shown only once there are at least eight weeks of history.|two": "يومان من الرصد حتى الآن. لا تظهر اتجاهات الأسعار ومدة البقاء في السوق وتأخيرات التسليم إلا بعد ثمانية أسابيع على الأقل من السجل.",
  "Days of observation so far. Price trends, time on market and delivery delays are shown only once there are at least eight weeks of history.|one": "يوم من الرصد حتى الآن. لا تظهر اتجاهات الأسعار ومدة البقاء في السوق وتأخيرات التسليم إلا بعد ثمانية أسابيع على الأقل من السجل.",
  "Every listing comes from AqarExit, a marketplace of contract transfers (تنازل) with the paid amount, the balance and the installments per unit. Figures describe the listings we index, not the whole Egyptian market.": "كل الإعلانات من عقار إكزت، منصة للتنازل عن العقود تنشر لكل وحدة المدفوع والمتبقي والأقساط. الأرقام تصف الإعلانات التي نرصدها، لا سوق مصر كله.",
  "Paste an AqarExit unit link": "الصق رابط وحدة من عقار إكزت",
  "Against the developer’s price today": "مقارنةً بسعر المطوّر اليوم",
  "This unit costs this much less, in today’s money, than a similar unit the developer is selling now.": "تكلّف هذه الوحدة أقل بهذا القدر، بقيمة اليوم، من وحدة مماثلة يبيعها المطوّر الآن.",
  "This unit costs this much more, in today’s money, than a similar unit the developer is selling now.": "تكلّف هذه الوحدة أكثر بهذا القدر، بقيمة اليوم، من وحدة مماثلة يبيعها المطوّر الآن.",
  "Developer’s price for this size": "سعر المطوّر لهذه المساحة",
  "Developer’s plan": "خطة سداد المطوّر",
  "Developer’s delivery": "تسليم المطوّر",
  "Developer’s price in today’s money": "سعر المطوّر بقيمة اليوم",
  "This unit in today’s money": "هذه الوحدة بقيمة اليوم",
  "From {n} of the developer’s current units in this compound, {size} m², listed on Nawy. Both prices are in today’s money: remaining installments are discounted at the same rate. Developer prices are list prices; negotiated discounts are not visible, and a resale unit often delivers sooner.": "من {n} وحدة يطرحها المطوّر حاليًا في هذا الكمبوند، بمساحة {size} م²، منشورة على ناوي. السعران بقيمة اليوم: تُخصم الأقساط المتبقية بالمعدل نفسه. أسعار المطوّر أسعار قوائم، ولا تظهر الخصومات المتفاوض عليها، ووحدة إعادة البيع كثيرًا ما تُسلَّم أسرع.",
  "Vs developer": "مقابل المطوّر",
  "Developer price": "سعر المطوّر",
  "Developer selling similar units": "المطوّر يبيع وحدات مماثلة",
  "Vs developer compares the unit, in today’s money, with the developer’s current price for similar units in the same compound.": "«مقابل المطوّر» يقارن الوحدة، بقيمة اليوم، بسعر المطوّر الحالي لوحدات مماثلة في الكمبوند نفسه.",
  "Resale against the developer": "إعادة البيع مقابل المطوّر",
  "Cheaper than buying": "أرخص من الشراء",
  "from the developer.": "من المطوّر.",
  "Resale units priced furthest below what the developer asks today for a similar unit in the same compound, with the same finishing, both in today’s money.": "وحدات إعادة البيع الأبعد تحت ما يطلبه المطوّر اليوم في وحدة مماثلة بالكمبوند نفسه وبالتشطيب نفسه، والسعران بقيمة اليوم.",
  "Resale units below the developer’s price": "وحدات إعادة بيع تحت سعر المطوّر",
  "All units against the developer’s price": "كل الوحدات مقابل سعر المطوّر",
  "Price benchmark: the developers’ current prices, never counted as resale": "مرجع أسعار: أسعار المطورين الحالية، ولا تُحتسب إعادة بيع أبدًا",
  "Developer’s finishing": "تشطيب وحدات المطوّر",
  "this unit: {finishing}": "هذه الوحدة: {finishing}",
  "The developer’s list price per m² since the seller signed in {year}: {contract} then, {today} now ({annual} a year). This unit is sold at its {year} contract price.": "سعر المتر في قائمة المطوّر منذ تعاقد البائع في {year}: {contract} وقتها، و{today} الآن ({annual} سنويًا). هذه الوحدة تُباع بسعر تعاقدها في {year}.",
  "The developer’s list price per m² since the seller signed in {year}: {contract} then, {today} now. This unit is sold at its {year} contract price.": "سعر المتر في قائمة المطوّر منذ تعاقد البائع في {year}: {contract} وقتها، و{today} الآن. هذه الوحدة تُباع بسعر تعاقدها في {year}.",
  "Contract signed": "سنة التعاقد",
  "Role": "الدور",
  "Compare a unit": "قارن وحدة",
  "Comparisons use published listing and developer list prices, not appraisals or completed sales. Confirm every detail with the seller and the developer.": "المقارنات مبنية على أسعار الإعلانات المنشورة وأسعار قوائم المطورين، لا على تقييمات أو صفقات مكتملة. تأكد من كل تفصيلة مع البائع والمطوّر.",
  "Is it really": "هل هي حقًا",
  "a good deal?": "صفقة جيدة؟",
  "Resale opportunities": "فرص إعادة البيع",
  "Resale units against what you could buy instead, in Egypt’s property market.": "وحدات إعادة البيع مقابل ما يمكنك شراؤه بدلًا منها، في سوق العقارات المصري.",
  "From {n} of the developer’s current units in this compound, {size} m², listed on Nawy. In today’s money, remaining installments on both sides are discounted at the same rate; the headline is the less favourable of the two gaps. Developer prices are list prices; negotiated discounts are not visible, and a resale unit often delivers sooner.": "من {n} وحدة يطرحها المطوّر حاليًا في هذا الكمبوند، بمساحة {size} م²، منشورة على ناوي. بقيمة اليوم تُخصم الأقساط المتبقية في الجانبين بالمعدل نفسه، والرقم الرئيسي هو الأقل تفضيلًا من الفجوتين. أسعار المطوّر أسعار قوائم، ولا تظهر الخصومات المتفاوض عليها، ووحدة إعادة البيع كثيرًا ما تُسلَّم أسرع.",
  "The developer’s units have a different finishing, so this comparison does not count towards the opportunity.": "وحدات المطوّر بتشطيب مختلف، لذلك لا تُحتسب هذه المقارنة في تقييم الفرصة.",
  "This unit costs this much less than a similar unit the developer is selling now, both as listed and in today’s money.": "تكلّف هذه الوحدة أقل بهذا القدر من وحدة مماثلة يبيعها المطوّر الآن، بالسعر المعلن وبقيمة اليوم معًا.",
  "This unit costs this much more than a similar unit the developer is selling now, on the less favourable of listed price and today’s money.": "تكلّف هذه الوحدة أكثر بهذا القدر من وحدة مماثلة يبيعها المطوّر الآن، على الأقل تفضيلًا من السعر المعلن وقيمة اليوم.",
  "This unit, as listed": "هذه الوحدة بالسعر المعلن",
  "A year: how the developer’s list price per m² has moved since the typical seller here signed.": "سنويًا: تغيّر سعر المتر في قائمة المطوّر منذ تعاقد البائع المعتاد هنا.",
  "Developer prices are its current units on Nawy. Each resale unit is compared with the developer’s units of the same type, finishing and similar size. Developer prices are list prices; negotiated discounts are not visible.": "أسعار المطوّر هي وحداته المطروحة حاليًا على ناوي. تُقارن كل وحدة إعادة بيع بوحدات المطوّر من النوع والتشطيب نفسيهما وبمساحة مماثلة. أسعار المطوّر أسعار قوائم، ولا تظهر الخصومات المتفاوض عليها.",
  "Developer today / m²": "المطوّر اليوم / م²",
  "Developer today / m², as listed": "المطوّر اليوم / م²، بالسعر المعلن",
  "Developer today / m², today’s money": "المطوّر اليوم / م²، بقيمة اليوم",
  "Developer units / resale units compared": "وحدات المطوّر / وحدات إعادة البيع المقارنة",
  "Latest developer delivery": "آخر موعد تسليم لدى المطوّر",
  "Median resale asking price": "وسيط السعر المطلوب لإعادة البيع",
  "Median resale contract price, signed around {year}": "وسيط سعر تعاقد إعادة البيع، تعاقد نحو {year}",
  "No resale unit here matches the developer’s units in type, size and finishing yet.": "لا توجد بعد وحدة إعادة بيع هنا تطابق وحدات المطوّر في النوع والمساحة والتشطيب.",
  "None of this developer’s current units on Nawy could be matched to a resale compound.": "لم نتمكن من مطابقة أي من وحدات هذا المطوّر الحالية على ناوي مع كمبوند فيه إعادة بيع.",
  "Not selling": "لا يبيع حاليًا",
  "Resale in today’s money / m²": "إعادة البيع بقيمة اليوم / م²",
  "Resale vs developer": "إعادة البيع مقابل المطوّر",
  "Strong or good opportunities": "فرص قوية أو جيدة",
  "The developer is not selling units in this compound on Nawy now.": "المطوّر لا يطرح وحدات في هذا الكمبوند على ناوي الآن.",
  "The typical resale unit here costs this much less than a similar unit the developer sells today, on the less favourable of listed price and today’s money.": "وحدة إعادة البيع المعتادة هنا تكلّف أقل بهذا القدر من وحدة مماثلة يبيعها المطوّر اليوم، على الأقل تفضيلًا من السعر المعلن وقيمة اليوم.",
  "The typical resale unit here costs this much more than a similar unit the developer sells today, on the less favourable of listed price and today’s money.": "وحدة إعادة البيع المعتادة هنا تكلّف أكثر بهذا القدر من وحدة مماثلة يبيعها المطوّر اليوم، على الأقل تفضيلًا من السعر المعلن وقيمة اليوم.",
  "Typical developer plan": "خطة المطوّر المعتادة",
  "{n} of {rated} compared": "{n} من {rated} وحدة مقارنة",
  "Cheaper than one comparison and dearer than the other.": "أرخص في إحدى المقارنتين وأغلى في الأخرى.",
  "Cheaper than what can be bought now: at least 5% under every comparison below, and 10% under one.": "أرخص مما يمكن شراؤه الآن: أقل بـ٥٪ على الأقل في كل مقارنة أدناه، وبـ١٠٪ في إحداها.",
  "Clearly cheaper than what can be bought now: at least 15% under every comparison below, and 25% under one.": "أرخص بوضوح مما يمكن شراؤه الآن: أقل بـ١٥٪ على الأقل في كل مقارنة أدناه، وبـ٢٥٪ في إحداها.",
  "Dearer than what can be bought now, as listed and in today’s money.": "أغلى مما يمكن شراؤه الآن، بالسعر المعلن وبقيمة اليوم.",
  "Different finishing": "تشطيب مختلف",
  "Each gap is the less favourable of the listed price and the price in today’s money. There is no fair price: Egypt publishes no resale sale prices.": "كل فجوة هي الأقل تفضيلًا من السعر المعلن والسعر بقيمة اليوم. لا يوجد «سعر عادل»: مصر لا تنشر أسعار بيع إعادة البيع.",
  "Far below everything comparable: most likely a listing error. Confirm the price before anything else.": "أقل بكثير من كل ما يماثلها: الأرجح أنه خطأ في الإعلان. تأكد من السعر قبل أي شيء.",
  "Good opportunity": "فرصة جيدة",
  "In line": "في المتوسط",
  "Mixed signals": "إشارات متعارضة",
  "No current price": "لا يوجد سعر حالي",
  "No like-for-like developer price and fewer than five similar units listed, so there is no verdict. The facts are below.": "لا يوجد سعر مطوّر مماثل، والوحدات المماثلة المعروضة أقل من خمس، لذلك لا يوجد حكم. الحقائق أدناه.",
  "Not enough to compare": "لا يكفي للمقارنة",
  "Opportunity": "الفرصة",
  "Priced about like what can be bought now.": "سعرها قريب مما يمكن شراؤه الآن.",
  "Pricier": "أغلى",
  "Rank in today’s money": "الترتيب بقيمة اليوم",
  "Similar means the same compound and unit type, within 1.5× the size, with the same finishing. Medians of the other units; listed prices are the sellers’ contract prices.": "المماثل يعني الكمبوند ونوع الوحدة نفسيهما، بمساحة في حدود ١٫٥ ضعف، وبالتشطيب نفسه. وسيط الوحدات الأخرى؛ الأسعار المعلنة هي أسعار تعاقد البائعين.",
  "Similar means the same compound and unit type, within 1.5× the size; too few share this unit’s finishing, so all finishings are included. Medians of the other units.": "المماثل يعني الكمبوند ونوع الوحدة نفسيهما، بمساحة في حدود ١٫٥ ضعف؛ الوحدات بتشطيب هذه الوحدة قليلة، فأُدرجت كل التشطيبات. وسيط الوحدات الأخرى.",
  "Similar units / m², as listed": "الوحدات المماثلة / م²، بالسعر المعلن",
  "Similar units / m², today’s money": "الوحدات المماثلة / م²، بقيمة اليوم",
  "Strong opportunity": "فرصة قوية",
  "This unit / m², as listed": "هذه الوحدة / م²، بالسعر المعلن",
  "This unit / m², today’s money": "هذه الوحدة / م²، بقيمة اليوم",
  "This unit costs this much less than the typical similar unit listed now in the same compound, both as listed and in today’s money.": "تكلّف هذه الوحدة أقل بهذا القدر من الوحدة المماثلة المعتادة المعروضة الآن في الكمبوند نفسه، بالسعر المعلن وبقيمة اليوم معًا.",
  "This unit costs this much more than the typical similar unit listed now in the same compound, on the less favourable of listed price and today’s money.": "تكلّف هذه الوحدة أكثر بهذا القدر من الوحدة المماثلة المعتادة المعروضة الآن في الكمبوند نفسه، على الأقل تفضيلًا من السعر المعلن وقيمة اليوم.",
  "Too few to rank": "قليلة جدًا للترتيب",
  "Vs similar units listed now": "مقابل الوحدات المماثلة المعروضة الآن",
  "Vs the developer today": "مقابل المطوّر اليوم",
  "{rank} of {n}, cheapest first": "{rank} من {n}، من الأرخص",
  "Units compared with the developer and with similar units": "وحدات مقارنة بالمطوّر وبالوحدات المماثلة",
  "Vs similar units": "مقابل الوحدات المماثلة",
  "other finishing": "تشطيب مختلف",
  "{rank} of {n}": "{rank} من {n}",
  "Compare up to three compounds, or up to three developers, on prices against the developer, opportunities, delivery and payment structure.": "قارن حتى ثلاثة كمبوندات أو ثلاثة مطورين في الأسعار مقابل المطوّر، والفرص، والتسليم، وهيكل السداد.",
  "resale / developer today, per m²": "إعادة البيع / المطوّر اليوم، للمتر",
  "Best opportunities first": "أفضل الفرص أولًا",
  "Compare a unit here": "قارن وحدة هنا",
  "Prices here": "الأسعار هنا",
  "What resale units here cost": "ما تكلّفه وحدات إعادة البيع هنا",
  "{developer}: resale {gap} vs its prices today, across {n} listings": "{developer}: إعادة البيع {gap} مقابل أسعاره اليوم، عبر {n} إعلان",
  "{developer}: {n} resale listings": "{developer}: {n} إعلان إعادة بيع",
  "{n} strong or good opportunities": "{n} فرصة قوية أو جيدة",
  "Compounds with their prices and opportunities": "الكمبوندات بأسعارها وفرصها",
  "Most opportunities": "الأكثر فرصًا",
  "Opportunities": "الفرص",
  "Resale / m²": "إعادة البيع / م²",
  "Resale / m² is the median listed price of the most listed class: AqarExit units sell at their original contract price. Developer today / m² is the developer’s current list price for that class on Nawy. Resale vs developer is the median gap of like-for-like units, on the less favourable of listed price and today’s money. Opportunities counts strong and good units.": "«إعادة البيع / م²» هو وسيط السعر المعلن للفئة الأكثر عرضًا: وحدات عقار إكزت تُباع بسعر تعاقدها الأصلي. «المطوّر اليوم / م²» هو سعر قائمة المطوّر الحالي لتلك الفئة على ناوي. «إعادة البيع مقابل المطوّر» هو وسيط فجوة الوحدات المماثلة، على الأقل تفضيلًا من السعر المعلن وقيمة اليوم. «الفرص» عدد الوحدات القوية والجيدة.",
  "Resale furthest above the developer": "إعادة البيع الأعلى من المطوّر",
  "Resale furthest below the developer": "إعادة البيع الأدنى من المطوّر",
  "What resale units cost in each compound, what the developer asks there today, and how many units are real opportunities.": "ما تكلّفه وحدات إعادة البيع في كل كمبوند، وما يطلبه المطوّر هناك اليوم، وكم وحدة منها فرصة حقيقية.",
  "Against the developer’s prices today": "مقارنةً بأسعار المطوّر اليوم",
  "Median gap of like-for-like resale units against the developer’s current price, on the less favourable of listed price and today’s money.": "وسيط فجوة وحدات إعادة البيع المماثلة مقابل سعر المطوّر الحالي، على الأقل تفضيلًا من السعر المعلن وقيمة اليوم.",
  "Median of {n} like-for-like resale units": "وسيط {n} وحدة إعادة بيع مماثلة",
  "No like-for-like developer price yet": "لا يوجد سعر مطوّر مماثل بعد",
  "Resale against the developer, compound by compound": "إعادة البيع مقابل المطوّر، كمبوندًا كمبوندًا",
  "Resale vs its prices today": "إعادة البيع مقابل أسعاره اليوم",
  "of {n} resale listings": "من {n} إعلان إعادة بيع",
  "{n} further compounds have no like-for-like developer price.": "{n} كمبوند آخر بلا سعر مطوّر مماثل.",
  "Developers with their resale units against their prices today": "المطورون ووحدات إعادة البيع لديهم مقابل أسعارهم اليوم",
  "How each developer’s resale units compare with what it sells today, how many are real opportunities, and what the stock looks like: delivery, payment plans and finishing.": "كيف تُقارن وحدات إعادة البيع لكل مطوّر بما يبيعه اليوم، وكم منها فرص حقيقية، وكيف يبدو المعروض: التسليم وخطط السداد والتشطيب.",
  "Resale vs developer is the median gap between the developer’s resale units and its own current units of the same type, finishing and similar size, on the less favourable of listed price and today’s money. A developer needs twenty such units to be ranked. Opportunities counts strong and good units.": "«إعادة البيع مقابل المطوّر» هو وسيط الفجوة بين وحدات إعادة البيع للمطوّر ووحداته الحالية من النوع والتشطيب نفسيهما وبمساحة مماثلة، على الأقل تفضيلًا من السعر المعلن وقيمة اليوم. يحتاج المطوّر إلى عشرين وحدة كهذه ليدخل الترتيب. «الفرص» عدد الوحدات القوية والجيدة.",
  "Against similar units listed now": "مقابل الوحدات المماثلة المعروضة الآن",
  "Choose the unit’s compound: every comparison is within its compound.": "اختر كمبوند الوحدة: كل مقارنة تتم داخل الكمبوند نفسه.",
  "Compare this unit": "قارن هذه الوحدة",
  "Comparing the unit…": "جارٍ مقارنة الوحدة…",
  "Describe the unit you were offered. Qayem puts its payment plan in today’s money and compares it with the developer’s price today and the similar units listed in the same compound.": "صِف الوحدة المعروضة عليك. يحوّل قيّم خطة سدادها إلى قيمة اليوم ويقارنها بسعر المطوّر اليوم وبالوحدات المماثلة المعروضة في الكمبوند نفسه.",
  "Fees as a share of the price": "الرسوم كنسبة من السعر",
  "Same compound and unit type, nearest in size first.": "الكمبوند ونوع الوحدة نفسهما، الأقرب في المساحة أولًا.",
  "Similar units": "وحدات مماثلة",
  "Similar units listed now": "وحدات مماثلة معروضة الآن",
  "We have no resale listings in that compound, so there is nothing to compare it with. Check the spelling, or choose a compound from the list.": "لا توجد لدينا إعلانات إعادة بيع في هذا الكمبوند، فلا شيء نقارنها به. راجع الاسم أو اختر كمبوندًا من القائمة.",
  "What this comparison cannot see": "ما لا تراه هذه المقارنة",
  "You will see how the unit compares with the developer’s price today and with the similar units listed in its compound, what its payment plan is worth today, and the units behind the comparison.": "سترى كيف تُقارن الوحدة بسعر المطوّر اليوم وبالوحدات المماثلة المعروضة في كمبوندها، وقيمة خطة سدادها اليوم، والوحدات التي بُنيت عليها المقارنة.",
  "Your comparison appears here": "تظهر مقارنتك هنا",
  "a real opportunity?": "فرصة حقيقية؟",
  "Against similar units now": "مقابل الوحدات المماثلة الآن",
  "Against the developer today": "مقابل المطوّر اليوم",
  "AqarExit sellers transfer their contract at the price they paid. Developers have raised their prices since, so an old contract can cost well below buying the same unit new.": "بائعو عقار إكزت يتنازلون عن عقودهم بالسعر الذي دفعوه. ورفع المطورون أسعارهم منذ ذلك الحين، فقد يكلّف عقد قديم أقل بكثير من شراء الوحدة نفسها جديدة.",
  "Best opportunities now": "أفضل الفرص الآن",
  "By developer": "حسب المطوّر",
  "Cheaper than": "أرخص مما",
  "what you could buy instead.": "يمكنك شراؤه بدلًا منها.",
  "Compounds with developer prices": "كمبوندات بأسعار مطورين",
  "Developer list prices per m²": "أسعار المتر في قوائم المطورين",
  "Developer prices since the contracts": "أسعار المطورين منذ التعاقدات",
  "Egypt publishes no resale sale prices, and AqarExit prices are the sellers’ old contract prices. So Qayem does not estimate what a unit is worth: it compares it with what you could buy instead today.": "مصر لا تنشر أسعار بيع إعادة البيع، وأسعار عقار إكزت هي أسعار التعاقد القديمة للبائعين. لذلك لا يقدّر قيّم قيمة الوحدة، بل يقارنها بما يمكنك شراؤه بدلًا منها اليوم.",
  "How a unit is judged": "كيف نحكم على الوحدة",
  "Median gap of each developer’s resale units against its own current units of the same type, finishing and similar size. Developers with at least 20 such units.": "وسيط فجوة وحدات إعادة البيع لكل مطوّر مقابل وحداته الحالية من النوع والتشطيب نفسيهما وبمساحة مماثلة. المطورون الذين لديهم ٢٠ وحدة كهذه على الأقل.",
  "Median yearly change between the price per m² a seller signed for and the developer’s price today for a similar unit in the same compound, across {n} units.": "وسيط التغيّر السنوي بين سعر المتر الذي تعاقد عليه البائع وسعر المطوّر اليوم لوحدة مماثلة في الكمبوند نفسه، عبر {n} وحدة.",
  "No fair price": "لا «سعر عادل»",
  "Not enough like-for-like developer prices yet.": "لا توجد أسعار مطورين مماثلة كافية بعد.",
  "Qayem compares every resale unit with what you could buy instead today: the developer’s own current price and the similar units listed in the same compound, both in today’s money.": "يقارن قيّم كل وحدة إعادة بيع بما يمكنك شراؤه بدلًا منها اليوم: سعر المطوّر الحالي نفسه والوحدات المماثلة المعروضة في الكمبوند نفسه، وكلاهما بقيمة اليوم.",
  "Resale opportunity index": "مؤشر فرص إعادة البيع",
  "Resale units compared": "وحدات إعادة بيع مقارنة",
  "Resale vs the developer’s prices today": "إعادة البيع مقابل أسعار المطوّر اليوم",
  "Same unit.": "الوحدة نفسها.",
  "Since the sellers signed": "منذ تعاقد البائعين",
  "What the developer asks now for a unit of the same type, finishing and similar size in the same compound, from its current listings on Nawy.": "ما يطلبه المطوّر الآن لوحدة من النوع والتشطيب نفسيهما وبمساحة مماثلة في الكمبوند نفسه، من وحداته المطروحة حاليًا على ناوي.",
  "Where the unit ranks among at least four similar units listed in the same compound. A unit is an opportunity only if it is cheaper both as listed and in today’s money.": "ترتيب الوحدة بين أربع وحدات مماثلة على الأقل معروضة في الكمبوند نفسه. الوحدة فرصة فقط إذا كانت أرخص بالسعر المعلن وبقيمة اليوم معًا.",
  "{annual} a year": "{annual} سنويًا",
  "{n} units compared": "{n} وحدة مقارنة",
  "A resale unit that delivers years before the developer’s new units is worth more for it. Both delivery dates are shown; the difference is not priced into the gap.": "وحدة إعادة البيع التي تُسلَّم قبل وحدات المطوّر الجديدة بسنوات تستحق أكثر لذلك. يظهر موعدا التسليم، لكن الفرق لا يُسعَّر في الفجوة.",
  "Against what you": "مقابل ما يمكنك",
  "could buy instead.": "شراؤه بدلًا منها.",
  "AqarExit units are listed at the owner’s original contract price, and Egypt publishes no resale sale prices. So Qayem does not say what a unit is worth; it compares it with what can be bought instead.": "وحدات عقار إكزت معروضة بسعر التعاقد الأصلي للمالك، ومصر لا تنشر أسعار بيع إعادة البيع. لذلك لا يقول قيّم كم تساوي الوحدة، بل يقارنها بما يمكن شراؤه بدلًا منها.",
  "At least {all} under every comparison that applies, and {one} under one of them.": "أقل بـ{all} على الأقل في كل مقارنة تنطبق، وبـ{one} في إحداها.",
  "At least {one} under one comparison and {up} over the other.": "أقل بـ{one} على الأقل في مقارنة، وأعلى بـ{up} في الأخرى.",
  "At least {up} over a comparison, as listed and in today’s money.": "أعلى بـ{up} على الأقل في مقارنة، بالسعر المعلن وبقيمة اليوم.",
  "Compared": "مقارنة",
  "Contract prices, not sale prices": "أسعار تعاقد، لا أسعار بيع",
  "Delivery is shown, not priced": "التسليم يُعرض ولا يُسعَّر",
  "Developer prices are list prices": "أسعار المطورين أسعار قوائم",
  "Developer prices come from the developers’ own current listings on Nawy. Negotiated discounts and private offers are not visible.": "تأتي أسعار المطورين من إعلاناتهم الحالية على ناوي. لا تظهر الخصومات المتفاوض عليها والعروض الخاصة.",
  "Each comparison is made twice: on the listed price, and in today’s money. A gap counts only on the less favourable of the two, so neither a long remaining plan nor the discount rate can make a deal on its own.": "تُجرى كل مقارنة مرتين: بالسعر المعلن، وبقيمة اليوم. تُحتسب الفجوة على الأقل تفضيلًا منهما فقط، فلا تصنع خطة سداد طويلة متبقية ولا معدل الخصم صفقة وحدهما.",
  "Every AqarExit unit is a contract transfer (تنازل), and AqarExit says whether it verified the contract and receipts. It is shown on every unit.": "كل وحدة على عقار إكزت تنازل عن عقد، ويذكر عقار إكزت إن كان قد تحقق من العقد والإيصالات. يظهر ذلك على كل وحدة.",
  "Every comparison": "كل مقارنة",
  "has to agree.": "يجب أن تتفق.",
  "For the median installment listing the cash value is {cut} below the headline. The developer’s plans are discounted the same way. Units whose terms are not fully published are not compared.": "في إعلان التقسيط الوسيط تقل القيمة النقدية عن السعر المعلن بمقدار {cut}. تُخصم خطط المطورين بالطريقة نفسها. الوحدات التي لم تُنشر شروطها كاملة لا تُقارن.",
  "How an opportunity": "كيف نحكم",
  "is judged.": "على الفرصة.",
  "Included: active sale listings in EGP between EGP 100,000 and 200 million, 20–5,000 m², with a property type and a district or compound. A complete run covers its defined scope, not the whole market.": "المشمول: إعلانات بيع نشطة بالجنيه بين ١٠٠ ألف و٢٠٠ مليون جنيه، بمساحة ٢٠–٥٬٠٠٠ م²، مع نوع عقار ومنطقة أو كمبوند. دورة الجمع المكتملة تغطي نطاقها المحدد، لا السوق كله.",
  "Indexed records, resale listings and compared listings by source": "السجلات المفهرسة وإعلانات إعادة البيع والإعلانات المقارنة حسب المصدر",
  "Level": "المستوى",
  "Levels": "المستويات",
  "More than {dev} under the developer or {peers} under similar units: most likely a listing error.": "أقل بأكثر من {dev} من المطوّر أو {peers} من الوحدات المماثلة: الأرجح أنه خطأ في الإعلان.",
  "No like-for-like developer price and fewer than {n} other similar units.": "لا يوجد سعر مطوّر مماثل، والوحدات المماثلة الأخرى أقل من {n}.",
  "Opportunity levels and their rules": "مستويات الفرص وقواعدها",
  "Qayem does not estimate a fair price. Egypt publishes no resale sale prices, and AqarExit lists each unit at its old contract price. Instead, every unit is compared with what could be bought instead today.": "لا يقدّر قيّم «سعرًا عادلًا». مصر لا تنشر أسعار بيع إعادة البيع، وعقار إكزت يعرض كل وحدة بسعر تعاقدها القديم. بدلًا من ذلك، تُقارن كل وحدة بما يمكن شراؤه بدلًا منها اليوم.",
  "Rule": "القاعدة",
  "See the rules": "اطّلع على القواعد",
  "Similar units now": "الوحدات المماثلة الآن",
  "Sources rarely publish them. A sea-view or garden unit can rightly cost more than similar units in its compound.": "نادرًا ما تنشرها المصادر. وحدة بإطلالة بحرية أو حديقة قد تكلّف أكثر من مثيلاتها في الكمبوند عن حق.",
  "The developer comparison counts only when the finishing matches: an unfinished unit is not a deal for being unfinished. Units are ranked by level, then those checked against both comparisons first, then by their average gap.": "تُحتسب مقارنة المطوّر فقط عند تطابق التشطيب: الوحدة غير المشطّبة ليست صفقة لأنها غير مشطّبة. تُرتَّب الوحدات حسب المستوى، ثم تتقدّم التي قورنت بالمقارنتين معًا، ثم حسب متوسط فجوتها.",
  "The developer today": "المطوّر اليوم",
  "The developer’s current units on Nawy in the same compound, of the same type and finishing, within 1.5× the size: the median of the nearest five, and at least two. {n} developer units in {c} compounds are matched; {u} resale units have a like-for-like developer price.": "وحدات المطوّر الحالية على ناوي في الكمبوند نفسه، من النوع والتشطيب نفسيهما، بمساحة في حدود ١٫٥ ضعف: وسيط أقرب خمس وحدات، واثنتان على الأقل. طابقنا {n} وحدة مطوّر في {c} كمبوند؛ و{u} وحدة إعادة بيع لها سعر مطوّر مماثل.",
  "The median like-for-like resale unit sits {gap} against the developer’s price today. Since the sellers signed, developer list prices per m² have moved {annual} a year (median of {n} units).": "وحدة إعادة البيع المماثلة الوسيطة عند {gap} مقابل سعر المطوّر اليوم. ومنذ تعاقد البائعين تغيّرت أسعار المتر في قوائم المطورين بمقدار {annual} سنويًا (وسيط {n} وحدة).",
  "The other resale units listed in the same compound, of the same type, within 1.5× the size, and of the same finishing when there are at least {n}. The unit is ranked against their median; {r} units have enough of them.": "وحدات إعادة البيع الأخرى المعروضة في الكمبوند نفسه، من النوع نفسه، بمساحة في حدود ١٫٥ ضعف، وبالتشطيب نفسه إن وُجدت {n} على الأقل. تُرتَّب الوحدة مقابل وسيطها؛ ولدى {r} وحدة ما يكفي منها.",
  "The same unit can be listed twice. Counts are listings.": "قد تُعرض الوحدة نفسها مرتين. الأعداد أعداد إعلانات.",
  "Two comparisons": "مقارنتان",
  "What a comparison": "ما لا تستطيع المقارنة",
  "Within the ranges above and below.": "بين الحدين أعلاه وأدناه.",
  "Adjust the details and compare again": "عدّل التفاصيل وقارن مجددًا",
  "Closest units in the same compound": "أقرب الوحدات في الكمبوند نفسه",
  "The similar units it is ranked against": "الوحدات المماثلة التي رُتّبت مقابلها",
  "Any level": "أي مستوى",
  "Every resale unit against the developer’s price today and the similar units listed in its compound, best opportunities first.": "كل وحدة إعادة بيع مقابل سعر المطوّر اليوم والوحدات المماثلة المعروضة في كمبوندها، أفضل الفرص أولًا.",
  "Vs developer compares the unit with the developer’s current price for similar units in the same compound; vs similar units compares it with the other resale units of the same type and size listed there, with its rank. Each gap is the less favourable of listed price and today’s money. A level is a prompt to look closer, not a recommendation.": "«مقابل المطوّر» يقارن الوحدة بسعر المطوّر الحالي لوحدات مماثلة في الكمبوند نفسه؛ و«مقابل الوحدات المماثلة» يقارنها بوحدات إعادة البيع الأخرى من النوع والمساحة نفسيهما المعروضة هناك، مع ترتيبها. كل فجوة هي الأقل تفضيلًا من السعر المعلن وقيمة اليوم. المستوى دعوة للنظر عن قرب، لا توصية.",
  "{n} opportunities": "{n} فرصة",
  "vs developer": "مقابل المطوّر",
  "{n} opportunities|one": "فرصة واحدة",
  "{n} opportunities|two": "فرصتان",
  "{n} opportunities|few": "{n} فرص",
  "{n} strong or good opportunities|one": "فرصة واحدة قوية أو جيدة",
  "{n} strong or good opportunities|two": "فرصتان قويتان أو جيدتان",
  "{n} strong or good opportunities|few": "{n} فرص قوية أو جيدة",
  // Navigation, sorting and sharing (2026-09-27 UX pass)
  Filters: "التصفية",
  "Furthest below the developer": "الأبعد تحت سعر المطوّر",
  "Furthest below similar units": "الأبعد تحت الوحدات المماثلة",
  "Price, low to high": "السعر: من الأقل إلى الأعلى",
  "Price, high to low": "السعر: من الأعلى إلى الأقل",
  "Cheapest per m² in today’s money": "الأرخص للمتر بقيمة اليوم",
  "Largest first": "الأكبر مساحةً أولًا",
  "Remove filter: {name}": "إزالة التصفية: {name}",
  "{n} developers": "{n} مطوّر",
  "{n} developers|one": "مطوّر واحد",
  "{n} developers|two": "مطوّران",
  "{n} developers|few": "{n} مطوّرين",
  "All {n} compounds": "كل الكمبوندات ({n})",
  "Where its resale units are": "أين تقع وحدات إعادة البيع لديه",
  "Add another compound": "أضف كمبوندًا آخر",
  "Add another developer": "أضف مطوّرًا آخر",
  "{value} in today’s money": "{value} بقيمة اليوم",
  Share: "مشاركة",
  Photos: "الصور",
  "signed {year}": "تعاقد {year}",
  "Show the nearest six": "اعرض أقرب ست وحدات فقط",
  "Show all {n} similar units": "اعرض كل الوحدات المماثلة ({n})",
  "All {n}: same compound and unit type, within 1.5× the size, and the same finishing when enough share it. Nearest in size first, with the year each seller signed.": "كلها ({n}): نفس الكمبوند ونوع الوحدة، بمساحة في حدود ١٫٥ ضعف، وبنفس التشطيب إن توفر منها ما يكفي. الأقرب مساحةً أولًا، مع سنة تعاقد كل بائع.",
  "Same compound and property class, nearest in size first, with the year each seller signed.": "نفس الكمبوند وفئة العقار، الأقرب مساحةً أولًا، مع سنة تعاقد كل بائع.",
  "Cheapest similar unit / m², today’s money": "أرخص وحدة مماثلة / م²، بقيمة اليوم",
  "Far below everything comparable, or even below the cheapest similar unit. It may be a listing error or an unusually early contract: confirm the price and the contract with the seller before anything else.": "أقل بكثير من كل ما يماثلها، أو حتى من أرخص وحدة مماثلة. قد يكون خطأً في الإعلان أو عقدًا مبكرًا على غير المعتاد: تأكد من السعر والعقد مع البائع قبل أي شيء.",
  "More than {dev} under the developer, {peers} under similar units, or {cheapest} under even the cheapest similar unit: verify it first. It may be a listing error or an unusually early contract.": "أقل بأكثر من {dev} من المطوّر، أو {peers} من الوحدات المماثلة، أو {cheapest} حتى من أرخص وحدة مماثلة: تحقّق منها أولًا. قد يكون خطأً في الإعلان أو عقدًا مبكرًا على غير المعتاد.",
  "How a gap is calculated": "كيف تُحسب الفجوة",
  "How today’s money is calculated": "كيف تُحسب القيمة بسعر اليوم",
  Gap: "الفجوة",
  "the larger of": "الأكبر من",
  and: "و",
  "Listed price per m²": "سعر المتر المعلن",
  "Comparison, listed": "سعر المتر للمقارنة، معلنًا",
  "Today’s-money price per m²": "سعر المتر بقيمة اليوم",
  "Comparison, in today’s money": "سعر المتر للمقارنة، بقيمة اليوم",
  "Price in today’s money": "السعر بقيمة اليوم",
  "Each remaining installment": "كل قسط متبقٍّ",
  t: "ن",
  "t: years until that installment is due.": "ن: عدد السنوات حتى موعد ذلك القسط.",
  "Photo {n} of {total}: {title}": "الصورة {n} من {total}: {title}",
  "Open photo {n}": "افتح الصورة {n}",
  "Photos published by {source}": "الصور كما نشرها {source}",
  "All {n} photos": "كل الصور ({n})",
  "All {n} photos|one": "صورة واحدة",
  "Close photos": "أغلق الصور",
  "Previous photo": "الصورة السابقة",
  "Next photo": "الصورة التالية",
  Save: "احفظ",
  Saved: "محفوظة",
  "The units and compounds": "الوحدات والكمبوندات",
  "Save a unit, or open a compound or developer and choose Watch.": "احفظ وحدة، أو افتح كمبوندًا أو مطوّرًا واختر «تابِع».",
  "Browse units": "تصفّح الوحدات",
  "Vs similar": "مقابل المماثلة",
  "Link copied": "نُسخ الرابط",
  "Copy the link from the address bar to share this unit.": "انسخ الرابط من شريط العنوان لمشاركة هذه الوحدة.",
  "At a glance": "نظرة سريعة",
  "Total price": "السعر الإجمالي",
  "Worth in today’s money": "قيمتها اليوم نقدًا",
  "Left, over {n} years": "المتبقي على {n} سنة",
  "Left, over {n} years|one": "المتبقي على سنة واحدة",
  "Left, over {n} years|two": "المتبقي على سنتين",
  "Left, over {n} years|few": "المتبقي على {n} سنوات",
  "Price per m²": "سعر المتر",
  "Bedrooms · bathrooms": "غرف النوم · الحمامات",
  "Cheaper on both": "أرخص في المقارنتين",
  "Two different comparisons, ranked separately. A unit cheaper than both the developer and similar resale units is marked “Cheaper on both”.": "مقارنتان مختلفتان، لكلٍّ منهما ترتيبها. الوحدة الأرخص من المطوّر ومن وحدات إعادة البيع المماثلة معًا تحمل علامة «أرخص في المقارنتين».",
  "Cheaper than the developer today": "أرخص من المطوّر اليوم",
  "Below what the developer asks today for a unit of the same type, finishing and similar size in the same compound. Mostly older contracts: developer prices have risen since the seller signed.": "أقل مما يطلبه المطوّر اليوم في وحدة من النوع والتشطيب نفسيهما وبمساحة مماثلة في الكمبوند نفسه. أغلبها عقود قديمة: رفع المطوّرون أسعارهم منذ أن وقّع البائع.",
  "Cheaper than other resale units": "أرخص من وحدات إعادة البيع الأخرى",
  "Below the typical price of at least four similar resale units listed in the same compound, as listed and in today’s money.": "أقل من السعر المعتاد لأربع وحدات إعادة بيع مماثلة على الأقل معروضة في الكمبوند نفسه، بالسعر المعلن وبقيمة اليوم.",
  "Resale units furthest below the developer’s price today": "وحدات إعادة البيع الأبعد تحت سعر المطوّر اليوم",
  "Resale units furthest below similar units in their compound": "وحدات إعادة البيع الأبعد تحت الوحدات المماثلة في الكمبوند نفسه",
  "All units, furthest below the developer": "كل الوحدات، الأبعد تحت سعر المطوّر أولًا",
  "All units, furthest below similar units": "كل الوحدات، الأبعد تحت الوحدات المماثلة أولًا",
  "Watch how it works": "شاهد كيف يعمل",
  "Watch how Qayem works": "شاهد كيف يعمل قيّم",
  "In Arabic": "بالعربية",
  "How Qayem works, a short film": "كيف يعمل قيّم، فيلم قصير",
  "Watch again": "شاهد مرة أخرى",
};
